### ISSUE TITLE
Provide arm64 images for Jenkins agents

### ISSUE THREAD

**Issue by kenrachynski** [jenkins-infra/helpdesk#2740]
### Service

Docker Hub

### Summary

I am trying to set up a Kubernetes cluster to build software for my cluster. This cluster happens to be running on arm64 hardware. I went to add a container template in my Kubernetes Cloud configuration against jenkinsciinfra/builder which looks like it includes its own docker in the container and is built on top of jenkinsci/inbound-agent. The only problem I see is that the only image architecture available on this image is amd64.

Could we please get multi-arch images for everything that the Jenkins project builds? or at least, jenkins-infra/docker-build.

**Comment by dduportal** [comment]
Hello @kenrachynski , I'm closing this issue as "duplicated" since https://github.com/jenkins-infra/docker-builder/issues/38 tracks the requirements specifically to the correct project.

(I'm sorry, I made you open the issue here thinking I would move it to jenkins-infra/docker-builder but you did good by cross opening 👍 )
