### ISSUE TITLE
Change the updatecli's bot commit profile (name/email)

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2753]
### Service

Other

### Summary

Almost all of the updatecli settings of the jenkins-infra organization have an `updatecli/values.yaml` file that sets up the attribute for the commits / PRs that it opens.

PR are usually opened using a GitHub App advertising itself as the `updatecli-bot` user.

We now have reached the amount of 3 contributors whom pointed out that the email of the bot commit is `updatebot@olblak.com` which should be changed :)

This issue is to track the work to change these email everywhere to `jenkins-infra-team@googlegroups.com`, e.g. the current infra private email.

**Comment by lemeurherve** [comment]
https://cs.github.com/?q=updatebot%40olblak.com+org%3Ajenkins-infra
22 files concerned

**Comment by dduportal** [comment]
As we do not sign cryptographically the bot commits, there should be no change on the GitHub side: the setting is "only" for `updatecli`. It's the same as a `git config --local user.email <new value>` to define the metdata to use when authoring a commit.

**Comment by timja** [comment]
Shouldn't it be using the details of the bot that's in use?

i.e. the github app account?

**Comment by lemeurherve** [comment]
As this email is only used for the bot commits I would use jenkins-infra-team@googlegroups.com as it's more useful for a future dev to contact on it than the github email alias, which doesn't have any use outside github

**Comment by timja** [comment]
I don't see it ever being useful for contact though? If you have a question raise an issue in the repo.
and we don't want people contacting us on there really except for very exceptional reasons.

I still think it would be better to use the GitHub app account which will link it to an actual user.

e.g. linked to github actions in this case, rather than a non existing github user
![image](https://user-images.githubusercontent.com/21194782/150522863-506951cd-2823-41d9-85b2-bbfba0b48546.png)

**Comment by lemeurherve** [comment]
The last remaining trace of `updatebot@olblak.com` are in archived repositories and will stay there.

**Comment by lemeurherve** [comment]
Closing this issue :)
