### ISSUE TITLE
Kubernetes Jenkins Agents: Garbage collect remaining pods

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#2773]
### Service

infra.ci.jenkins.io

### Summary

Quite often, the controller restarts or pipeline tests, or even "unplanned" connectivity issues are letting a bunch of pods that are not acting as agents. It costs us some $ and create chaos for maintenance...

- Some are in `Completed` state (easy to catch)
- Some are in `Running` state (we can agree that after more than 12h these can be deleted)
- Some are in `Error` state (same let's remove them after 12h)

A garbage collecting procedure should be created (a Kubernetes Job? A regular Jenkins Job ? A GtiHub Action ? Something else?) to avoid these leftovers.

It's the case on all controller with Kubernetes agents: not only infra.ci, but also release.ci and ci.jenkins.io.

NOTE: it seems that the actual pod configuration on ci.jenkins.io has less leftovers. Maybe the pod config has something that helps pod to be recycled.

**Comment by basil** [comment]
Conceptually, such "sweepers" are no different than finalizers in Java.

- Like finalizers, there is no guarantee that the sweeper will be executed promptly (see [JLS § 12.6](https://docs.oracle.com/javase/specs/jls/se8/html/jls-12.html#jls-12.6)). It can take an arbitrarily long time for the finalizer/sweeper to be executed.
- Not only is there no guarantee that the finalizer/sweeper will be executed promptly, but also there is no guarantee that the finalizer/sweeper will be executed at all. Therefore, relying on a finalizer/sweeper to keep the system stable is a mistake.

To avoid these problems, systems programmers traditionally rely on explicit termination and require consumers to invoke the explicit terminator whenever a resource is no longer needed. In this style of programming, a consumer that fails to explicitly release its resource when it is no longer needed is in error.

One valid use case for finalizers (sweepers, in my analogy) is described by Joshua Bloch in _Effective Java_ (emphasis not mine):

> One is to act as a "safety net" in case the owner of an object forgets to call its explicit termination method. While there's no guarantee that the finalizer will be invoked promptly, it may be better to free the resource late than never, in those (hopefully rare) cases when the client fails to call the explicit termination method. But **the finalizer should log a warning if it finds that the resource has not been terminated,** as this indicates a bug in the client code, which should be fixed.

The same logic applies here. A sweeper can and should be written to clean up stray pods as a "safety net", but the existence of a stray pod in the first place is a bug that needs to be fixed with the sweeper acting merely as a workaround for that bug. Therefore the implementation of the sweeper should log warnings loudly, and these warnings should be periodically triaged by a cross-functional team of developers and operators to ensure that the root cause is determined and the bug fixed. This feedback loop needs to be designed into the process from the outset in order to ensure that the root cause is addressed.

**Comment by dduportal** [comment]
I’ll personally stay on a gc script or kube jobs, as i am not smart enough to handle things such as what you described

**Comment by basil** [comment]
> I’ll personally stay on a gc script or kube jobs, as i am not smart enough to handle things such as what you described

You are smart. You are blessed. You can do anything. We can get there together, one step at a time.

**Comment by dduportal** [comment]
For information, I'm closing this as there is already a "GC" in Kubernetes that removes pods after 24h so no need to.
