### ISSUE TITLE
Unable to log in to jenkins.io account

### ISSUE THREAD

**Issue by gschueler** [jenkins-infra/helpdesk#2793]
### Service

Accounts

### Summary

I'm unable to log in to jenkins.io account. I've reset my password multiple times, and tried logging in with email or userid.  If I try with email it fails, if I try with userid it first says i must fill a captcha, then fails.

userid: gschueler

TIA

**Comment by dduportal** [comment]
Hi @gschueler, in order to prove your identity, could you send an email to jenkins-infra-team <at> googlegroups.com, from the email registered for your Jenkins account please?

**Comment by dduportal** [comment]
Email received, an answer was sent to you @gschueler .

**Comment by dduportal** [comment]
Closing as @gschueler confirmed by email that everything was solved:

> Thanks, I can now log in to [issues.jenkins.io](http://issues.jenkins.io/) using my userid.
>
> -- 
> Greg


For info, Greg's account was marked as "requires verify email" state in Keycloak's backend: his password was correctly changed but the loggin was still refused because of this attribute set by Keycloak into LDAP.

Verifying the email + reseting the password worked as expected.
