### ISSUE TITLE
`maven-11` builds not starting on ci.jenkins.io

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#2802]
### Service

ci.jenkins.io

### Summary

At least maven-11 builds not spawning on ci.jenkins.io
~500 builds in queue

e.g. https://ci.jenkins.io/blue/organizations/jenkins/Infra%2Frepository-permissions-updater/detail/master/28037/pipeline

**Comment by lemeurherve** [comment]
After rebooting twice the instance, it started spawning maven-11 jobs again.

The build queue has been processed, we're currently studying the root cause.

**Comment by dduportal** [comment]
Root cause is on me: while working on https://github.com/jenkins-infra/helpdesk/issues/2800 and https://github.com/jenkins-infra/helpdesk/issues/2801, I updated all the plugins because the updated credential for Azure wasn't being used. 

The combination of VM reboot + plugins wide upgrade seems to have trigger a lock issue: I should have restarted the instance 2 times after the plugin update.
