### ISSUE TITLE
Want containerized Java 17 Windows agents

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#2822]
### Service

ci.jenkins.io

### Summary

We have long had a `maven-11` label for containerized Java 11 Linux agents, and a `maven-11-windows` label for containerized Java 11 Windows agents.

jenkins-infra/jenkins-infra#2021 added a `maven-17` label for containerized Java 17 Linux agents, and we are now using it in core components and plugins, but there is still no `maven-17-windows` label for containerized Java 17 Windows agents. Please add one.

There is no urgency for this request, as we are not blocked on this for Platform SIG work at the moment. But this will be needed sometime in the next 3-9 months.

### Reproduction steps

Run a Jenkins job with the `maven-17-windows` label and observe that it hangs because no such label is defined.

**Comment by dduportal** [comment]
Yes, that would be a good idea to have an upstream Java 17 image on  jenkinsci, and then having the infra image "FROM" this image.

**Comment by lemeurherve** [comment]
@timja I'm not sure what setting you are talking about, is it the `core.longpaths` one?

**Comment by timja** [comment]
yes that

**Comment by dduportal** [comment]
For information, we are working on this topic: we are in the process of consolidating all agent images for ci.jenkins.io into a single definition system (ref.  https://github.com/jenkins-infra/packer-images/issues/285) so that wether a build runs on a VM or a container, that should not change the embeded tools.

Since all the VM agents already have JDK8, JDK11 and JDK17 on both Ubuntu 20.04 and Windows 2019, that would be the same for the Docker agents as well.

**Comment by dduportal** [comment]
Status update: The Linux container images for agents have switched to the packer image "all in one" last week.

Next step is https://github.com/jenkins-infra/packer-images/pull/321 to build "all in one" Windows container

**Comment by dduportal** [comment]
As the "all in one" image takes too much time for Windows containers, we should add a JDK17 template now in ttps://github.com/jenkins-infra/docker-inbound-agents/tree/main/maven

**Comment by smerle33** [comment]
this PR https://github.com/jenkinsci/jenkins/pull/7429 should close this issue.
