### ISSUE TITLE
Request access to Jenkins project VPN

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#2881]
### Service(s)

VPN

### Summary

Docker openvpn PR: https://github.com/jenkins-infra/docker-openvpn/pull/156 and https://github.com/jenkins-infra/docker-openvpn/pull/158

**Comment by lemeurherve** [comment]
It's to perform the next Jenkins release isn't it?

**Comment by MarkEWaite** [comment]
+1 from me for the Jenkins release lead for 2.332.3 to be granted access to the VPN.  @NotMyFault is a strong Jenkins contributor with a history of helping the project in the UX SIG and in the Docs SIG.

**Comment by NotMyFault** [comment]
> +1 from me for the Jenkins release lead for 2.332.3 to be granted access to the VPN. @NotMyFault is a strong Jenkins contributor with a history of helping the project in the UX SIG and in the Docs SIG.

Thanks for the heads up, I got already everything set up so far, just having a hard time with Tunnelblick, as it asks for a username and password instead of using my provided keypair from the .ovpn file.

**Comment by dduportal** [comment]
Oooh good catch @NotMyFault ! The Readme at https://github.com/jenkins-infra/docker-openvpn#howto-get-client-access does not mention (I was sure it was). Sorry for that, incoming readme PR :)

Can you close the issue here if everything works for you?

**Comment by NotMyFault** [comment]
> Can you close the issue here if everything works for you?

I can access release.ci fine, but trusted.ci doesn't resolve.

**Comment by dduportal** [comment]
@NotMyFault As far as I remember, the release check list mention a job to run on trusted.ci to have the controller image built at the end of the release.
This is an "todo item" on our side, to migrate this job to release.ci (so it is available).

As trusted is not behind the VPN, but in another network, is that ok if you delegate this step to someone with access (ideally me, Mark or Herve)? Accessing trusted is a bit tedious and I would avoid it as much as possible.

(things are moving quite quickly and it explains why there is this discrepancy in the process).

Ping @MarkEWaite @timja WDYT to update the release check list for now, since @NotMyFault is currently annoyed by it, like Ildefonso was last LTS ?

**Comment by MarkEWaite** [comment]
> Ping @MarkEWaite @timja WDYT to update the release check list for now, since @NotMyFault is currently annoyed by it, like Ildefonso was last LTS ?

No objection from me if the release checklist is updated to guide the release lead to ask one of the people with access to trusted.ci.jenkins.io to perform those short term operations that we eventually plan to move elsewhere.

**Comment by NotMyFault** [comment]
> As trusted is not behind the VPN, but in another network, is that ok if you delegate this step to someone with access (ideally me, Mark or Herve)? Accessing trusted is a bit tedious and I would avoid it as much as possible.

I'm fine with it, I know several people who can access it and likewise I'll find someone to run the job. Though in the long run it would be handy to have it available on release.ci too to get everything under one hood.

**Comment by dduportal** [comment]
For info: readme update for VPN on https://github.com/jenkins-infra/docker-openvpn/pull/159
