### ISSUE TITLE
Creating a node fails on Windows when jenkins has not been installed on the C: drive

### ISSUE THREAD

**Issue by micktion** [jenkins-infra/helpdesk#3088]
### Service(s)

Other

### Summary

After creating a node I can see it is attempting to execute the following command and failing with the error "Unable to access jarfile remoting.jar"

cd "D:\Jenkins\" && java  -jar remoting.jar -workDir D:\Jenkins\ -jar-cache D:\Jenkins\/remoting/jarCache'.

This is failing as cd does not change the drive. 

It should be cd /d "D:\Jenkins\". 

### Reproduction steps

Install jenkins on drive other than the C:

1. Go to Manage Jenkins -> Manage Nodes and Clouds
2. Click  + New Node
3. Fill in the details and select Launch agents via SSH
4. Click Save 
5. Inspect the log for the node

_No response_

**Comment by dduportal** [comment]
Hi @micktion , the issue tracker in this repository is only for the Jenkins public Infrastructure as stated in the README: `Support for Infrastructure related issues for the Jenkins project.`.

Could you open this issue on the Jenkins issue tracker at Support for Infrastructure related issues for the Jenkins project. where the behavior of Jenkins (and its plugin) is tracked, as your request sounds legit at first sight?



Closing the issue as "not planned" because unrelated to the scope of this repository

**Comment by micktion** [comment]
Hi sorry, was directed here from this tweet...

https://twitter.com/MarkEWaite/status/1555622594237214720

I was having issues getting into the jenkins jira issue tracker... However I had another look and I did actually finally receive an email for the account (a whole day later)

I've created the following ticket...

https://issues.jenkins.io/browse/JENKINS-69275

**Comment by dduportal** [comment]
> 

Thanks for the pointer, I did not have the context.

It looks like your account works again, many thanks for opening the issue!
