### ISSUE TITLE
Pipeline failing from 'maven-windows' nodes offline

### ISSUE THREAD

**Issue by curveenk** [jenkins-infra/helpdesk#3094]
Problem with the [Redirects from ci.jenkins.io](https://www.jenkins.io/infra/ci-redirects/) page, [source file](https://github.com/jenkins-infra/jenkins.io/blob/master/content/infra/ci-redirects.adoc)

We have encountered failed pipelines due to the following error  across all pull requests today:
## Screenshots 

![image](https://user-images.githubusercontent.com/103989779/184077411-dc3c3c03-0e69-4283-bc91-326c9cad7be4.png)

When accessed to ci jenkins dashboard, we observed several agents are offline:

![image](https://user-images.githubusercontent.com/103989779/184078381-df27ffe3-7a0b-4df2-b7a4-4f53abb45b30.png)

It worked in the our previous PR that was merged.

## Possible Solution 

N/A

**Comment by dduportal** [comment]
Hi @curveenk , thanks for raising this issue! We are looking on this issue right now.

Note: I've transfered the issue to https://github.com/jenkins-infra/helpdesk which is Jenkins public infrastructure issue tracker.

**Comment by dduportal** [comment]
It looks like that this problem is a side effect of my manual testings for #3090 yesterday.

I've just rollbacked all the configuration for the ACI maven 8 agents for now to unblock builds, and monitoring builds.

I'll resume the work for #3090 once the build queue will be emptied.

**Comment by dduportal** [comment]
@curveenk I now can see aci-maven-8 container agents spawned successfully and handling builds. 

Can you confirm by closing the issue (or adding a message if not fixed for you) please?

Many thanks for reporting!

**Comment by curveenk** [comment]
Thanks for your prompt response!

Have just re-run the pipeline and observed a different message now:
_Waiting for next available executor on ‘maven-windows’_

Can I give you the confirmation once it passes the queueing stage?

In the meantime, I would also like to understand from you regarding the availability, range and differences across other container agents supported, such as maven 11 and etc. Is there a tendency of better supports and maintenance over the newer version than maven 8, or perhaps users are encouraged to move into a specific version?

**Comment by dduportal** [comment]
> Thanks for your prompt response!

You are welcome. Do not hesitate to open issues here if it is infrastructure related instead of jenkins.io's tracker: you'll get prompt answer here (while the infra team might not always monitor the jenkins.io's website tracker).

> Have just re-run the pipeline and observed a different message now: _Waiting for next available executor on ‘maven-windows’_

This message is expected: it tells you that the Jenkins controller does not *immediatly* an available agent but it usually is starting an agent in the cloud.
Since there is delay between the job starting and when an agent, with the specified tools, is ready to take your build, this message might stay for 1-2 min (usually).

Rule of thumb is: if your build is not on the build queue, you should expect an agent ready in 1 to 5 min. More than 5 min means "start checking the state of ci.jenkins.io".

> Can I give you the confirmation once it passes the queueing stage?

Absolutely: it is even better to wait for your build completion to confirm (as an infra people, I prefer my end users to be happy with the outcome of the platform ;) ).

> In the meantime, I would also like to understand from you regarding the availability, range and differences across other container agents supported, such as maven 11 and etc. Is there a tendency of better supports and maintenance over the newer version than maven 8, or perhaps users are encouraged to move into a specific version?

There is difference, as for today (but that will change in the near future) between Linux and Windows containers agents on ci.jenkins.io:

- Linux containers are executed in one of the different Kubernetes clusters (1 in amazon, 1 in Digital Ocean, and soon 2 others on other cloud providers).
- Windows containers are executed in Azure Container Instance service (hence the acronym "ACI")

Sometimes, Azure is overloaded and the ACI containers takes a bit more time to start (5-10 min instead of 1-3 min).
The same can happen sometimes for the Linux container agents when there is a high build pressure (usually when there is a jenkinsci/bom build). Waiting ~30,40 min is sufficient.

There should be no avaialability/range/performance difference, from an infrastructure point of view, either you run a maven-jdk8, maven-jdk11 (or soon maven-jdk17) agent, wether on Linux or Windows, because there are the same.
Except of course when the infra-team is working on these templates like, unlucky you, yesterday.


Sorry for the inconvenience! I've described the technical details of the incident in the following comment: https://github.com/jenkins-infra/helpdesk/issues/3090#issuecomment-1211683884 including the short term + long term fixes.

**Comment by curveenk** [comment]
Looks like the issue is unblocked now 👍  
Thanks for the fix!

It's good to also know from you that JDK8 is still good to go and that doesn't impact the service we receive. 

Thanks again and I will now close this issue.

**Comment by dduportal** [comment]
> Looks like the issue is unblocked now 👍 Thanks for the fix!
> 
> It's good to also know from you that JDK8 is still good to go and that doesn't impact the service we receive.
> 
> Thanks again and I will now close this issue.

@curveenk JDK8 is still supported, but JDK11 is strongly recommended as Jenkins will make JDK11 mandatory for the september release. The infrastructure will drop JDK8 only after Jenkins will have definitively dropped it so no worries.
