### ISSUE TITLE
missleading timestamps on get.jenkins.io/war/latest/jenkins.war

### ISSUE THREAD

**Issue by jtnord** [jenkins-infra/helpdesk#3100]
### Service(s)

Other

### Summary

According to the timestamps https://get.jenkins.io/war/latest/jenkins.war was last updated in 2020

This is not the case and if you download the file you can see it is 2.364 (which is the latest at the time of writing).

However this causes confusion as it appears it has not been updated.

### Reproduction steps

1. go to https://get.jenkins.io/war/

Notice the modification data on `latest`  (possibly ok if this is a directory and the children are symlink)s.

2. go to https://get.jenkins.io/war/latest/

Notice the modification date on the files is still in 2020

Expected result, the timestamps shown in the web interface correspond to (approximatly) the time of publishing of the war.

**Comment by dduportal** [comment]
It's the whole subject of #3034:

- Symlinks are updated on each release on the update.jenkins.io and archives.jenkins.io by the publication scripts (as well as mirrors, because rsync updates symlinks on remote machines).
- But for get.jenkins.io, an azure blob storage is used (way cheaper than disks), but the "latest" directories are not updated (since not overriden remotely and symlinks are dereferenced)


The idea would be to update the "latest" dir on each publication (war or plugins) or find a way to make blobxfer to update symlinks.

Closing as duplicate, I'll cherry-pick your message.
