### ISSUE TITLE
Migration of jenkins(se) from on prem to google cloud vmware engine

### ISSUE THREAD

**Issue by joyjitpal100** [jenkins-infra/helpdesk#3102]
### Describe your use-case which is not covered by existing documentation.

I am migrating jenkins(se) from on prem to Google cloud vmware engine, please confirm whether Jenkins is supported in GCVE

**Comment by dduportal** [comment]
Hi, thanks for raising this issue.

We are closing it because this issue tracker is  for `Support for Infrastructure related issues for the Jenkins project.` as per the [README](https://github.com/jenkins-infra/helpdesk).

Since your question is legit, could you open a discussion in the community forum at https://community.jenkins.io?
By doing so, you will ensure to reach a broader set of people who can help you and give you help.

Thanks!
