### ISSUE TITLE
reset my login

### ISSUE THREAD

**Issue by JeremyMarshall** [jenkins-infra/helpdesk#3150]
### Service(s)

ci.jenkins.io, LDAP

### Summary

hi not sure if this is the right place

I need to release a plunin of mine and I've lost my login details. my username was jeremym and my email is jeremystuartmarshall@gmail.com

and this is my plugin https://plugins.jenkins.io/matrix-groovy-execution-strategy/

thanks
Jeremy

**Comment by dduportal** [comment]
Hi @JeremyMarshall , you can usually reset your account from https://accounts.jenkins.io/login.

I've initated the reset password on your account, you should receive an email. Please change it on your first login.

Please note that you might want to wait ~3h until your new credentials are synchronized to repo.jenkins-ci.org (batch runs every 3 hours) if you plan to do a manual release of your plugin (otherwise look at https://www.jenkins.io/doc/developer/publishing/releasing-cd/).

Let us know once you've recovered your account.

**Comment by JeremyMarshall** [comment]
all good, thanks. Please close
