### ISSUE TITLE
Unable to Remove Deprecated Plugins from Jenkins (Static Analysis Utilities)

### ISSUE THREAD

**Issue by KnifeHand** [jenkins-infra/helpdesk#3155]
### Service(s)

plugins.jenkins.io

### Summary

While performing plugin updates and Jenkins upgrade I was unable to remove Static Analysis Utilities plugins.  Removal is not an option via the GUI.  If I remove the plugins from the docker build and then from the plugins directory, Jenkins is still reporting this as a CVE.  Suspect the plugin is a dependency for other installed plugins but I was unable to figure it out. 

Here is the list of plugins I currently have installed [plugins.txt](https://github.com/jenkins-infra/helpdesk/files/9680483/plugins.txt)

Warnings have been published for the following currently installed components:
[Static Analysis Utilities 1.96](http://wiki.jenkins-ci.org/x/CwDgAQ)
    [Stored XSS vulnerability](https://www.jenkins.io/security/advisory/2020-11-04/#SECURITY-1907)

Any help resolving this would be most appreciated.

### Reproduction steps

1. Update/remove depricated plugins.txt
2. Install configs from plugins.txt
3. Observe installed plugins from Jenkins UI where Static Analysis Utilities still installed
4. Attempt to remove Static Analysis via GUI and fail.

[plugins.txt](https://github.com/jenkins-infra/helpdesk/files/9680541/plugins.txt)

**Comment by dduportal** [comment]
Hi @KnifeHand thanks for reporting the issue: you are providing a complete set of elements to diagnose.

However, as this issue tracker is dedicated to the Jenkins Infrastructure Services, we'll close this issue because it's related to Jenkins itself (or one of these plugins).

May we ask you to open a topic on community.jenkins.io if you prefer asking for help from the community, or opening an issue on issues.jenkins.io if you feel like it is a bug in Jenkins or in one of its plugins?
