### ISSUE TITLE
https://ci.jenkins.io/job/Infra/job/stories/ is not handling PRs

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/helpdesk#3157]
### Service(s)

GitHub

### Summary

When people want to contribute, and something goes wrong, its only see on infra.ci.jenkins.io, which isn't helpful for non vpn people.

PRs should be built and tested on the public infra.

**Comment by dduportal** [comment]
Hello @halkeye ,

I thought that the GitHub Status Checks were enabled for this job on infra.ci, but they are not.
Would having GitHub check enough for your request (to provide build output in GitHub)?

Otherwise we'll have to revamp the `Jenkinsfile` a bit (to have "pure" CI in ci.jenkins.io and "pure CD" in infra.ci).

Which road would you prefer?

**Comment by dduportal** [comment]
If I understand correctly, the goal is to have:

- PRs built and tested (ci.jenkins.io)
- PRs deployed to a preview environment (infra.ci)
- Principal branch built and tested (ci.jenkins.io)
- Principal  branch deployed to production (infra.ci)

=> is that correct?

**Comment by halkeye** [comment]
yes, that sounds right.

**Comment by dduportal** [comment]
So the idea is to merge both pipelines so the steps will be the same on both systems.

In order to do so:

- Let's use a pod template to execute all steps. As infra.ci uses `jenkinsciinfra/builder` (and should switch to the docker image created by packer in a near future), let's add a pod template named `jnlp-webbuilder` on both ci.jenkins.io and infra.ci.jenkins.io (so no more pod template in the repo nor pipeline)
  - https://github.com/jenkins-infra/jenkins-infra/pull/2458 for ci.jenkins.io
  - TBD for infra.ci
- Then let's merge the pipelines into a single one
  - Same agent definition, in Kubernetes for faster agent allocation and reproductibility
  - Preview deployment will only be run on infra.ci (but the keywords must be available in the pipeline-library though as per @halkeye help in https://github.com/jenkins-infra/pipeline-library/pull/510)

**Comment by dduportal** [comment]
- https://ci.jenkins.io/job/Websites/job/stories/ created as a multibranch pipeline (easier to handle changes)

**Comment by dduportal** [comment]
> * https://ci.jenkins.io/job/Websites/job/stories/ created as a multibranch pipeline (easier to handle changes)

Added the repository to the GitHub app ci.jenkins.io for jenkins-infra organization, otherwise the scan repository log fails on the new job. @halkeye that would explain why PR weren't working on the previous job in ci.jenkins.io -> "Infra" (GH org. folder" -> "stories".
