### ISSUE TITLE
update center json returning 404

### ISSUE THREAD

**Issue by aimetci** [jenkins-infra/helpdesk#3161]
### Service(s)

Archives

### Summary

https://updates.jenkins-ci.org/dynamic-stable-2.361.2/update-center.json returning 404 
also
13:34:49 + wget https://updates.jenkins-ci.org/dynamic-stable-stable/update-center.json
13:34:49 --2022-10-05 13:34:49--  https://updates.jenkins-ci.org/dynamic-stable-stable/update-center.json
13:34:49 Resolving updates.jenkins-ci.org (updates.jenkins-ci.org)... 52.202.51.185
13:34:49 Connecting to updates.jenkins-ci.org (updates.jenkins-ci.org)|52.202.51.185|:443... connected.
13:34:49 HTTP request sent, awaiting response... 404 Not Found

### Reproduction steps

13:34:49 + wget https://updates.jenkins-ci.org/dynamic-stable-stable/update-center.json
13:34:49 --2022-10-05 13:34:49--  https://updates.jenkins-ci.org/dynamic-stable-stable/update-center.json
13:34:49 Resolving updates.jenkins-ci.org (updates.jenkins-ci.org)... 52.202.51.185
13:34:49 Connecting to updates.jenkins-ci.org (updates.jenkins-ci.org)|52.202.51.185|:443... connected.
13:34:49 HTTP request sent, awaiting response... 404 Not Found

**Comment by aimetci** [comment]
can someone look at this?

**Comment by MarkEWaite** [comment]
> can someone look at this?

The use case is very specific for your case @aimetci .  We've had no reports from other users of any issue with the update center and we have higher priority topics that need our focus.  We have other issues that affect many more users and will receive attention first.

You may want to consider using the plugin installation manager tool to download plugins, instead of downloading JSON file and processing it with your own tools.

**Comment by aimetci** [comment]
Mark how can I get all the plugins compatible with release 2.361.2 for me to download then in our artifactory?

Thank you!

**Comment by MarkEWaite** [comment]
I maintain my list of compatible plugins that I use with these commands (using the [jenkins-plugins-cli.sh script](https://github.com/jenkinsci/docker/blob/master/jenkins-plugin-cli.sh) from the container image):

```bash
$ ./jenkins-plugin-cli.sh --jenkins-version 2.361.2 -d ref/plugins -f plugins.txt --no-download --available-updates -o txt > x && mv x plugins.txt
$ ./jenkins-plugin-cli.sh --jenkins-version 2.361.2 -d ref/plugins -f plugins.txt
```

The first command creates a modified `plugins.txt` file with the plugins that have been updated since the last run.  I commit that to the source code repository.

The second command downloads the plugins list as defined in the plugins.txt file.

I started with a plugins.txt file generated from my Jenkins instance.  I used the Jenkins script console output to run the following script:

```groovy
Jenkins.instance.pluginManager.plugins
    .collect()
    .sort { it.getShortName() }
    .each {
        plugin -> println("${plugin.getShortName()}:${plugin.getVersion()}")
    }
return
```

**Comment by aimetci** [comment]
Damien  - any update?

**Comment by daniel-beck** [comment]
> Mark how can I get all the plugins compatible with release 2.361.2 for me to download then in our artifactory?

[Do like Jenkins does](https://updates.jenkins.io/#version-specific-update-sites):

`curl --location https://updates.jenkins.io/update-center.json?version=2.361.2`

This is not a defect, but an unsupported wild-ass guess at which update center tiers exist [contrary to documentation](https://github.com/jenkins-infra/update-center2/tree/master/site#dynamic-update-site-tiers).
