### ISSUE TITLE
Kubernetes Plugin Terminates Windows Pod intermittently when PodRetention is set to Never

### ISSUE THREAD

**Issue by rajuvadarevu** [jenkins-infra/helpdesk#3216]
### Service(s)

ci.jenkins.io, plugins.jenkins.io

### Summary

Jenkins Version: 2.332.2
Kubernetes Plugin: 3580.v78271e5631dc
This is an Intermittent Issue
We are using Azure AKS managed service to host windows agent pods
When we set PodRetenction to Never, the plugin terminates the pod saying the Task is complete even though its not, but the same pipeline works successfully when we set PodRetention to Always

Here are the Kubernetes Plugin logs taken from org.csanchez.jenkins.plugins.kubernetes Log Recorder:
Failure case:
[FailureCase.txt](https://github.com/jenkins-infra/helpdesk/files/9926122/FailureCase.txt)
Success case:
[SuccessCase.txt](https://github.com/jenkins-infra/helpdesk/files/9926123/SuccessCase.txt)

As we see, one of the difference is, in Success case, the Kubernetes Plugin executed org.csanchez.jenkins.plugins.kubernetes.KubernetesFactoryAdapter createClient and not in Failure case

**Comment by dduportal** [comment]
Hi @rajuvadarevu , this issue tracker is only about the public Jenkins Infrastructure as per https://github.com/jenkins-infra/helpdesk#help-desk.

Your problem seems related to the Kubernetes plugin: you might want to go to the [plugin page](https://plugins.jenkins.io/kubernetes/) and report your issue (right column, section "Links", there should be a "Open Issue" link).
