### ISSUE TITLE
Node.js missing on agent

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3222]
### Service(s)

ci.jenkins.io

### Summary

I glanced over the recent failures in https://github.com/jenkinsci/.github and figured, that something changed between build 46 and 47 onwards: https://ci.jenkins.io/job/Tools/job/.github/job/master/

The recent failures claim, that `/usr/bin/env: ‘node’: No such file or directory`.

**Comment by lemeurherve** [comment]
NodeJS is present as we can see [in the logs](https://ci.jenkins.io/job/Tools/job/.github/job/master/49/console):

> 16:58:35  node --version
> 16:58:35  v16.13.1

The problem comes from `ajv` which doesn't seem to inherit of the parent `PATH`.

**Comment by NotMyFault** [comment]
> The problem comes from `ajv` which doesn't seem to inherit of the parent `PATH`.

Looks like the path changed between 46 and 49 from `/home/jenkins/workspace` to `/home/jenkins/agent/workspace/` 🤔

**Comment by dduportal** [comment]
> > The problem comes from `ajv` which doesn't seem to inherit of the parent `PATH`.
> 
> Looks like the path changed between 46 and 49 from `/home/jenkins/workspace` to `/home/jenkins/agent/workspace/` 🤔

Absolutely. I forgot to mention it in previous issue, I'll check this up to get archives.

Following https://github.com/jenkinsci/docker-ssh-agent/pull/165, we discovered that the `/home/jenkins` should not be the root of the agent working dir (using a volume removes everything from the  homedir, including `.ssh`, `.asdf` and `.m2` for instance.

But there should be absolutely NOTHING in a pipeline pointing to this path though.


As pointed by @lemeurherve , the problem seems to be with the command `ajv` which uses a shebang `#!/usr/bin/env node` to revole the `node` binary.
But since the Docker image changed from https://github.com/jenkins-infra/docker-inbound-agents/blob/main/node/Dockerfile to https://github.com/jenkins-infra/docker-builder/blob/main/Dockerfile with `asdf` to install `nodejs` then it seems to break some weird command lines like this one.

Gotta diagnose more. Ping @halkeye @timja if you have seen such issues with ASDF / node, etc.
I wonder if we should keep asdf for nodejs honestly.

**Comment by dduportal** [comment]
Wip: trying to reporudce the issue on an agent: replayed a build and added a "sleep" whicl accessing the pod agent interactively

**Comment by dduportal** [comment]
Fix applied on ci.jenkins.io.

Build https://ci.jenkins.io/job/Tools/job/.github/job/master/58/ was successful.
