### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by lakshmineha577** [jenkins-infra/helpdesk#3224]
### Service(s)

infra.ci.jenkins.io, weekly.ci.jenkins.io

### Summary

Email message didn't come to my email for resetting my password for jenkins login.

**Comment by MarkEWaite** [comment]
Needs more information to understand what happened and what might be done about it.

Did you attempt to reset your password through https://accounts.jenkins.io/ ?  If not, that is the place where password reset must be performed.

What is the username of the Jenkins account so that we can confirm that it has the expected email address?

**Comment by lakshmineha577** [comment]
User name : Neha_577

**Comment by MarkEWaite** [comment]
I've sent an update to the email address on file there.  I'll send you a separate email message from my gmail account as well.

**Comment by dduportal** [comment]
Closing as no answer and no details from the requester
