### ISSUE TITLE
New repo for jenkins board

### ISSUE THREAD

**Issue by halkeye** [jenkins-infra/helpdesk#3271]
### Service(s)

GitHub

### Summary

The google doc used to record all governance meeting minutes for the last few years has gotten really really long and hard to load.

Mark and I decided to archive all old meeting minutes to github. Oleg wants to have a repo for board issues and projects for tracking purposes.

I have access to create a new "board" repo in jenkins-infra, but not jenkinsci. So opening a ticket. I think infra is the right place to put it, oleg suggests jenkinsci, i'll leave it up to infra team.

**Comment by NotMyFault** [comment]
I agree with Oleg's proposal. I think we should create the repo in the jenkinsci org. The infra org feels more for actual jenkins infrastructure related topics, rather than board, SIG, or officer documentation.

**Comment by dduportal** [comment]
The organization `jenkinsci` sounds a better location.

However, a reminder that we (infra team) recently created https://github.com/jenkins-infra/governance-meetings to host the former meeting minutes that were stored on the lettuce VM, in order to have the website meetings.jenkins-ci.org up again.

Would that make sense to migrate this repository to `jenkinsci` to use it?

**Comment by halkeye** [comment]
I would recommend it be called governance not governance-meeting so it can be used for more things, like maybe sponsorship details.

Based on our last few meetings, it doesn't sound like anyone will object, and I can't transfer to jenkinsci anyways, so feel free to transfer (and rename?) At your leisure.

**Comment by timja** [comment]
Done, (should really have been in the hosting repo as a new hosting request)

https://github.com/jenkinsci/governance/

**Comment by timja** [comment]
Would be good to store action items there in the issue tracker rather than in the giant google doc, and would help delegating them out I think

**Comment by timja** [comment]
Re-opening for adjusting DNS

**Comment by timja** [comment]
Domain is verified on jenkinsci and DNS updated in Azure. 1 hour TTL on DNS

**Comment by daniel-beck** [comment]
> The organization `jenkinsci` sounds a better location.

Regarding `jenkinsci` vs. `jenkins-infra`, I had a conversation with @dduportal about this, since I was surprised about it quite a bit.

Historically we haven't been super clean about this (`jenkins-infra` is also relatively recent), but note how a lot of "not strictly infra" repos are in the `jenkins-infra` org. Some examples:

* https://github.com/jenkins-infra/usage-in-plugins
* https://github.com/jenkins-infra/usage-log-decrypter
* https://github.com/jenkins-infra/repository-permissions-updater

These are only tangentially (at most) infra related, because they use the infra.

Now we serve meetings.jenkins-ci.org from a `jenkinsci` repo. How does that make sense?

----

The way I think about it (which isn't canonical but seems useful):

* `jenkinsci` is stuff that ends up as deliverables to end users
* `jenkins-infra` is stuff that doesn't

Now, obviously, websites are "delivered" in a way, but you'd rarely say you download them (`wget -r` doesn't count 😁).

Examples of non-core/plugin stuff in jenkinsci is https://github.com/jenkinsci/packaging and https://github.com/jenkinsci/docker which are both tied fairly closely to infra, but since those produce "deliverables", they fit.

In this model, moving the repo to `jenkinsci` for _any_ future use model (archive only, logs only, general governance repo) makes no sense. So I would appreciate if you could explain, given current repo locations, how moving this repo into `jenkinsci` makes sense to you.

**Comment by halkeye** [comment]
@daniel-beck Who is the "you" you are expecting a response from? I agree with you, if it's not installable by the end user it's part of the infra but many disagreed which is why I originally asked for a new repo but didn't care where as long as people agreed

**Comment by daniel-beck** [comment]
@halkeye 

> Who is the "you" you are expecting a response from?

I guess everyone who wanted it in `jenkinsci` (minus Damien who seems to agree with me after my explanation).

**Comment by dduportal** [comment]
- Revert of the "archived minutes" repository tracked in https://github.com/jenkins-infra/helpdesk/issues/3277
- @NotMyFault @MarkEWaite @olegnenashev Can I let you decide on the next governance, the name of the governance repository you would want? You should have the permission to create it but if you need any assistance please ask here.

**Comment by dduportal** [comment]
Ping on this topic: was the board able to decide what to do with the repository? Should we close the issue here or is the jenkins-infra team needed?

**Comment by NotMyFault** [comment]
The point was skipped during the last meeting, I'll allude to it again in a couple of weeks.

**Comment by lemeurherve** [comment]
Another point in favour of putting this in @jenkins-infra: easier to search and gather information.

For example, I needed to find about the mails provider "SendGrid", a search in @jenkins-infra repositories returned the account-app and governance meeting notes from 2017, without the need to search elsewhere.

**Comment by MarkEWaite** [comment]
> Another point in favour of putting this in @jenkins-infra: easier to search and gather information.
> 
> For example, I needed to find about the mails provider "SendGrid", a search in @jenkins-infra repositories returned the account-app and governance meeting notes from 2017, without the need to search elsewhere.

The governance meeting notes include a comment that @oleg-nenashev has a preference for jenkinsci rather than jenkins-infra, but I'm not clear on the details.  @oleg-nenashev can you provide further details on your concern?  I'm fine with it in either location.

**Comment by NotMyFault** [comment]
I have no strong preference where the archive is hosted from, just fyi.

**Comment by halkeye** [comment]
[meetings.md](https://github.com/jenkins-infra/helpdesk/files/11154360/meetings.md)

**Comment by halkeye** [comment]
the export i ran back then

**Comment by MarkEWaite** [comment]
I've submitted a pull request with an updated meetings markdown using the same markdown converter that @halkeye used.  Pull request is:

* https://github.com/jenkins-infra/governance-meetings-archives/pull/10

@NotMyFault I think we should use that repository as the ongoing location for governance meeting notes in markdown.  That would mean we decide not to apply your ["retire" pull request](https://github.com/jenkins-infra/governance-meetings-archives/pull/9).  Would you be OK with that?  I'd like to clear the "archive the meeting notes" action item from my list.
