### ISSUE TITLE
In reference to issue #3183

### ISSUE THREAD

**Issue by hostedvideorn** [jenkins-infra/helpdesk#3338]
In reference to issue #3183

For some reason when trying to synchronize the Jenkins repository lately I am getting the following error

Errors:
404, message='Not Found', url=URL('https://ftp-nyc.osuosl.org/pub/jenkins/redhat/jenkins-2.233-1.1.noarch.rpm')

**Comment by hostedvideorn** [comment]
@dduportal

**Comment by hostedvideorn** [comment]
Packages are being downloaded from https://pkg.jenkins.io/redhat/ - maybe the metadata has old info

**Comment by hostedvideorn** [comment]
Hi @dduportal - any comments / updates on this issue? thanks

**Comment by MarkEWaite** [comment]
https://ftp-nyc.osuosl.org/pub/jenkins/redhat/jenkins-2.333-1.1.noarch.rpm downloads correctly for me.

https://get.jenkins.io/redhat/jenkins-2.333-1.1.noarch.rpm?mirrorlist shows the expected set of mirrors that have the file available.

https://get.jenkins.io/redhat/jenkins-2.333-1.1.noarch.rpm downloads the file from my nearest mirror site as well

I don't think that we should spend any further effort attempting to make the Red Hat proprietary tool "Red Hat Satellite" work.  We don't have access to that tool.  We don't have a compelling use case for that tool, since our mirrors already provide global distribution.  If someone from Red Hat wants to contribute a pull request to the Jenkins project to resolve it, we're willing to consider that pull request.

**Comment by hostedvideorn** [comment]
Hi @MarkEWaite, I never asked for the tool to be fixed because the tool works fine.
The file is jenkins-**2.233**-1.1.noarch.rpm and not jenkins-2.333-1.1.noarch.rpm 

When trying to download https://ftp-nyc.osuosl.org/pub/jenkins/redhat/jenkins-2.233-1.1.noarch.rpm I got a 404  which means not found. I tried it manually as well with the same results. 

![image](https://user-images.githubusercontent.com/15238386/213040491-1a986c09-bf1b-4586-9c5d-985942aa9a5f.png)

**Comment by MarkEWaite** [comment]
Jenkins mirrors do not commit to retain all historical releases.  The mirror you're trying to access (ftp-nyc.osuosl.org) does not have that file.  It likely had that file at one time, but the file has been removed from the mirror.

Jenkins 2.233 is a weekly that was released 33 months ago.  The Jenkins project stopped delivering security fixes for that release over 32 months ago.  The Jenkins update center does not support versions older than 2.324 for weekly releases and 2.319.1 for LTS releases (see ["Choosing a Jenkins version to build against"](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/)).

If you must have that rpm file, it is available from https://archives.jenkins.io/redhat/jenkins-2.233-1.1.noarch.rpm.

I'm closing this ticket.  No further work is planned on it.

**Comment by dduportal** [comment]
Hi @hostedvideorn , the 404 indicates that the file is no longer mirrored because it is too old.

We could spend some time on this to improve (such as ensuring a fallback to the mirror archives.jenkins.io) but the team does not have the time to spend on such an old version of Jenkins (2.233 line is almost 3 years old and not even a LTS line).

We have set this issue as "infra-team-sync-next" to mark that we cannot spend time on diagnostic for now, and we do not have any ETA.

**Comment by hostedvideorn** [comment]
@dduportal - right. I don't want to download that file. I was just pointing that the metadata still had that file and when trying to download from the mirror it was giving a 404 and throwing the error shown. I was pointing it out so maybe the metadata could be refreshed or something. That's all.

**Comment by hostedvideorn** [comment]
> Jenkins mirrors do not commit to retain all historical releases. The mirror you're trying to access (ftp-nyc.osuosl.org) does not have that file. It likely had that file at one time, but the file has been removed from the mirror.
> 
> Jenkins 2.233 is a weekly that was released 33 months ago. The Jenkins project stopped delivering security fixes for that release over 32 months ago. The Jenkins update center does not support versions older than 2.324 for weekly releases and 2.319.1 for LTS releases (see ["Choosing a Jenkins version to build against"](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/)).
> 
> If you must have that rpm file, it is available from https://archives.jenkins.io/redhat/jenkins-2.233-1.1.noarch.rpm.
> 
> I'm closing this ticket. No further work is planned on it.

Hi @MarkEWaite  - please see comments above. I don't plan to download this file but just pointing that the metadata still had it and because of that it was throwing the error shown.

**Comment by hostedvideorn** [comment]
Thanks @timja - much appreciated

**Comment by hostedvideorn** [comment]
> Re-opening in case there's something that can be done about the metadata not containing releases forever when mirrors won't have them

I'm following up to know if the team has been able to make any more progress on this.

**Comment by dduportal** [comment]
@hostedvideorn We'll let you know when we'll have time to prioritize this issue.

Alas we have other major tasks to work that will take us until mid-February before we can properly focus here. Sorry for that.

**Comment by dduportal** [comment]
Update: we are working on solutions. Some of our fellow Jenkins users in China faces the same kind of problem due to the network. We might have a solution as explained in https://github.com/jenkins-infra/helpdesk/issues/3636#issuecomment-1658708087.

Please note that we do not provide any ETA: it's our top priority but we don't know obstacle on the road of this change.

**Comment by dduportal** [comment]
Hi @hostedvideorn , we recently defined archives.jenkins.io as the fallback for mirror downloads, instead of the OSUOSL. It ensures we always have the file in the fallback.

You can see this behavior with https://get.jenkins.io/redhat/jenkins-2.233-1.1.noarch.rpm?mirrorlist: the mirror redirector system is now able to serve the file.

I've set up a local pulp mirror with and it worked without errors: the metadata keeps being served by `pkg.jenkins.io` and are specifying `get.jenkins.io` for binaries to download.

As such, I am closing this issue as solved: can you comment and reopen if it is not the case please (with error message up to date)?
