### ISSUE TITLE
https://pkg.jenkins.io/redhat-stable/ Does not have latest LTS 2.375.2

### ISSUE THREAD

**Issue by jcastor** [jenkins-infra/helpdesk#3367]
### Service(s)

pkg.jenkins.io

### Summary

The red-hat rpm repo here: https://pkg.jenkins.io/redhat-stable/, does not seem to have been updated with the latest LTS line, it still has 2.357 listed as the current weekly line and 2.361.1 as the LTS line, according to https://www.jenkins.io/download/, 2.375.2 should be the latest LTS and 2.389 is the latest weekly.

### Reproduction steps

Go to https://pkg.jenkins.io/redhat-stable/

**Comment by dduportal** [comment]
Hi @jcastor , thanks for raising the issue.

We (Jenkins Infra) team acknowledge that the `index.html` page show old versions and believe it is only the visual HTML file that is not updated anymore (since... quite some time).


But it's only visual: the repository sould install the latest versions as expected (there should be no problem for you to proceed).
As a side note, the page https://www.jenkins.io/download/ can be considered as a source of truth (at least in short term for you) until we diagnose why the HTML file is not updated (and fix it).

Note for the jenkins-infra team: we should also check other distributions if there is an idnex.html not updated.

**Comment by MarkEWaite** [comment]
That is intentional.  The page is listing the supported Java versions and the first release that requires those Java versions.

The page intentionally does not list all versions.  I recommend that we do not change this because that page is not intended as an index of available versions, it is a statement of the first versions that support or require a particular Java release.

**Comment by dduportal** [comment]
My apologize, I felt under the same trap as @jcastor . The page is up to date as expected, so I'll close the issue.

Feel free to reopen if you still have an issue.
