### ISSUE TITLE
Can no longer test PCT incrementals in `jenkinsci/bom`

### ISSUE THREAD

**Issue by basil** [jenkins-infra/helpdesk#3392]
### Service(s)

Artifact-caching-proxy

### Summary

I could test https://github.com/jenkinsci/bom/pull/1764 locally successfully, but [the CI build failed](https://ci.jenkins.io/job/Tools/job/bom/job/PR-1764/2/consoleFull) with …

```
+ pct=/home/jenkins/.m2/repository/org/jenkins-ci/tests/plugins-compat-tester-cli/1249.v93361f4ff6dd/plugins-compat-tester-cli-1249.v93361f4ff6dd.jar
+ '[' -f /home/jenkins/.m2/repository/org/jenkins-ci/tests/plugins-compat-tester-cli/1249.v93361f4ff6dd/plugins-compat-tester-cli-1249.v93361f4ff6dd.jar ']'
+ mvn -B -ntp -s /home/jenkins/agent/workspace/Tools_bom_PR-1764@tmp/config821646324268693295tmp dependency:get -Dartifact=org.jenkins-ci.tests:plugins-compat-tester-cli:1249.v93361f4ff6dd:jar -DremoteRepositories=https://repo.jenkins-ci.org/public/,https://repo.jenkins-ci.org/incrementals/ -Dtransitive=false
[…]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.5.0:get (default-cli) on project parent: Couldn't download artifact: Could not find artifact org.jenkins-ci.tests:plugins-compat-tester-cli:jar:1249.v93361f4ff6dd in aws-proxy (https://repo.aws.jenkins.io/public/) -> [Help 1]
```

Looks like the `mvn` command is trying to fetch from both `public` and `incrementals` but somehow when the mirror is used it is only looking in `public` (which is why regular builds work) but not `incrementals` (which is why I cannot test PCT changes right now).

### Reproduction steps

To see it failing, run a PR build of https://github.com/jenkinsci/bom/pull/1764. To see it passing, check out that PR locally and run `PLUGINS=text-finder TEST=InjectedTest bash local-test.sh`.

**Comment by dduportal** [comment]
I'll delegate to @lemeurherve but it seems it's on the injected `settings.xml` side, because the proxy itself halready had cached the dependency: https://repo.aws.jenkins.io/artifactory/incrementals/org/jenkins-ci/tests/plugins-compat-tester-cli/1249.v93361f4ff6dd/ exists.

**Comment by lemeurherve** [comment]
Thanks for opening the issue.

To resolve the ambiguity for incrementals when there is [a `*` in the `mirrorOf` section of the settings.xml](https://github.com/jenkins-infra/jenkins-infra/blob/afbf4a075c08317a95c94a6d01e2c20c5a842c48/dist/profile/templates/jenkinscontroller/casc/artifact-caching-proxy.yaml.erb#L14) (which we want in order to cache the maximum of Maven repositories), [a new layout has been applied to the Maven command](https://github.com/jenkinsci/bom/commit/f032fe1506e3c86b878b360b66916cd9d73436a1) in the BOM repository, fixing its build.

For information, if you ever find yourself in a similar situation, blocked by the artifact caching proxy, you can add a `skip-artifact-caching-proxy` on your pull requests to bypass it.

**Comment by basil** [comment]
Thank you!
