### ISSUE TITLE
We can't access our plugin account

### ISSUE THREAD

**Issue by emelkomurcu** [jenkins-infra/helpdesk#3393]
### Type(s) of account issue

I've lost my password

### Summary

Hi, 
I'm working as a software engineer in Opsgenie, Atlassian. We have an account for managing our opsgenie plugin. We can't log in and reset the password. 
Here is the user name: opsgenieplugin
We don't know the email address and password. Can you please help us?

### jenkins.io account username

opsgenieplugin

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
Hi @emelkomurcu , this plugin has not been updated since 2 years and is suffering from a security issue.

As such, we (the jenkins infrastructure team) need a set of formal proofs to reset the asociated account.

To get started, we require the following elements:
- First, we need an email to jenkins-infra-team@googlegroups.com from a member of the Atlassian OpsGenie team
- Second, we need a member of the [official GitHub Atlassian organization](https://github.com/atlassian) to add a comment in this issue (because your GitHub account is not sufficient for identity proof)

After these 2 first points, we'll get back to you (and the implied members) for further steps.

**Comment by daniel-beck** [comment]
The account email address is `eng-heimdall-ank@atlassian.com`. Ideally you'd be able to get access to this email address, even if only temporarily, to be able to resolve this yourself.

**Comment by dduportal** [comment]
Gentle ping @emelkomurcu

**Comment by emelkomurcu** [comment]
Hi,
As a developer in the Opsgenie product, we are members of https://github.com/opsgenie instead of Atlassian github organization. I need to contact the team for the required steps you mentioned. 
Then I'll contact you for further steps. Thanks for your help

**Comment by dduportal** [comment]
I'm going to close this issue as no answer back from @emelkomurcu .

If you have any news, feel free to re-open the issue.
