### ISSUE TITLE
Old email provider deleted

### ISSUE THREAD

**Issue by antoinetran** [jenkins-infra/helpdesk#3397]
### Type(s) of account issue

I've lost my password

### Summary

Hi,

my account antoinetran is linked to this email antoine.tran@thales-services.fr. This email has been deleted and will never be accessible again. I have a new professional email: xxxx@thalesgroup.com. So I lost my password (well, the password was saved in my Firefox but it does not work anymore?) and I cannot recover it with email.

Can you change it to my new email? Thank you.
Antoine

### jenkins.io account username

antoinetran

### jenkins.io account email

antoine.tran@thales-services.fr

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by antoinetran** [comment]
It would be great to delete email info when this is processed, because I received too many spams because my email was public :)

**Comment by dduportal** [comment]
Hi @antoinetran , thanks for raising the issue.

In order to start the identity approval process, we need the 2 following elements:

- Can you send an email from your new email account to be used, to jenkins-infra-team@googlegroups.com (private mailing list)
- Can we ask someone from the [official ThalesGroup GitHub organization](https://github.com/ThalesGroup) to comment the issue here, since your GitHub account is not enough for now?

Thanks in advance!

**Comment by antoinetran** [comment]
Account recovered.
