### ISSUE TITLE
Check if we could replace `blobxfer` by `azcopy`

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#3414]
As we've encountered some issues with blobxfer recently (#3411), and as [its last release is quite dated](https://github.com/Azure/blobxfer/releases/tag/1.11.0), check if we could replace it with an `az-cli` command like what's done in the pipeline library: https://github.com/jenkins-infra/pipeline-library/blob/93b13be5d876d90d8cd145b11c9f9fe457239db9/vars/publishReports.groovy#L55-L59

Related:
- #3034
- #3100 
- #3411

**Comment by lemeurherve** [comment]
We'll use https://github.com/Azure/azure-storage-azcopy.

**Comment by lemeurherve** [comment]
Current references to `blobxfer` (excluding some updatecli manifests and co):
- https://github.com/jenkins-infra/plugin-site/
  - https://github.com/jenkins-infra/plugin-site/blob/18eab578599559b3488ab3c80e0442831fd38851/Jenkinsfile_k8s#L137-L147
  - https://github.com/jenkins-infra/plugin-site/blob/92cd7d43e815e9ebdc1600bded5ef7c181b8a15f/PodTemplates.yaml#L32
- https://github.com/jenkins-infra/jenkins.io
  - https://github.com/jenkins-infra/jenkins.io/blob/70dcb0ea954715e3868eefe11ce2f3becb2beac7/Jenkinsfile#L93
  - https://github.com/jenkins-infra/jenkins.io/blob/705c356ea780015e81b280f0b51115e8e6fa41f0/scripts/blobxfer
- https://github.com/jenkins-infra/docker-builder/
  - https://github.com/jenkins-infra/docker-builder/blob/01feb906896c26cfc999865f8c8ec39a5ca95a9c/Dockerfile#L44-L47
- https://github.com/jenkins-infra/javadoc/
  - https://github.com/jenkins-infra/javadoc/blob/65f66c065530570beebdbedabdd6bccb26b0bcf8/Jenkinsfile#L61-L75
  - https://github.com/jenkins-infra/javadoc/blob/035941b3709dff3723dc61abe413f076c8da9923/scripts/blobxfer
- https://github.com/jenkins-infra/mirror-scripts/
  - https://github.com/jenkins-infra/mirror-scripts/blob/503b7acaec844465b9dd7fc4e55d1ba5c6ded758/sync-recent-releases.sh#L32 (called from Update Center job on trusted.ci.jenkins.io)
  - https://github.com/jenkins-infra/mirror-scripts/blob/195f59824d380a91576056fa4449dcc8d501ccc9/batch-upload.bash#L11-L19
  - https://github.com/jenkins-infra/mirror-scripts/blob/bebd7675616a2073173b241ddf5021d098c5f2b4/sync.sh#L75-L76
- https://github.com/jenkins-infra/cn.jenkins.io/blob/a09a9483bcc48d773f00173c4f28a780c21b0446/Jenkinsfile#L109 (won't change)
- https://github.com/jenkins-infra/jenkins-infra/blob/c6016c12be8a369df8b4855d57fc4e1f4d925657/dist/profile/manifests/pkgrepo.pp#L103-L143

Corresponding storage accounts:
- `prodpluginsite`, File Share: `pluginsite`
- `prodjenkinsio`, File Share: `jenkinsio` (and also `cnjenkinsio` & `zhjenkinsio`)
- `prodjavadoc`, File Share: `javadoc`
- `prodjenkinsreleases`, File Shares: `mirrorbits` & `website`


To replace `blobxfer` by `azcopy` for manipulating these files shares, SAS tokens need to be generated and stored as credentials (blobxfer is using the access key of the storage accounts, much less grain fined).
To do so, these storage accounts and file shares have to be imported as code in https://github.com/jenkins-infra/azure first.

The plan is to:
- [ ] Import as code storage accounts and file shares
  - [ ] `prodpluginsite`, File Share: `pluginsite`
  - [ ] `prodjenkinsio`, File Share: `jenkinsio`
  - [ ] `prodjavadoc`, File Share: `javadoc`
  - [ ] `prodjenkinsreleases`, File Shares: `mirrorbits` & `website`
- [ ] Create corresponding SAS tokens
- [ ] Create credentials with these SAS tokens
- [ ] Replace `blobxfer` by `azcopy` (cf refs above)
  - [ ] In https://github.com/jenkins-infra/plugin-site/
  - [ ] In https://github.com/jenkins-infra/jenkins.io/
  - [ ] In https://github.com/jenkins-infra/javadoc/
  - [ ] In https://github.com/jenkins-infra/mirror-scripts/
- [ ] Ensure everything is working as intended
- [ ] Remove `blobxfer` from our builder image and VMs.
  - [ ] Remove from https://github.com/jenkins-infra/docker-builder/
  - [ ] Remove from https://github.com/jenkins-infra/jenkins-infra/
  
  
Note: if time permits, we should also replace `az storage` by `azcopy` in `infra.publishReports`: https://github.com/jenkins-infra/pipeline-library/blob/350e1b561b633ae204265ce89bca20edfce3c02f/vars/publishReports.groovy#L55-L59

**Comment by lemeurherve** [comment]
Oh... I'll look into that instead then, thanks for the info @timja

**Comment by dduportal** [comment]
This plan looks good and exhaustive. The only (blocking) point will be the credential: we need to document what is the exact kind of token required and what is the process to revoke it

**Comment by lemeurherve** [comment]
> Ideally a service principal / managed identity / workload identity should be used instead. SaS tokens are irrevocable and are worse than account keys in some ways

Unfortunately azcopy supports only SAS token for File Share: https://learn.microsoft.com/en-gb/azure/storage/common/storage-use-azcopy-v10#authorize-azcopy

According to https://learn.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal#manually-rotate-access-keys and https://learn.microsoft.com/en-us/rest/api/storageservices/create-service-sas#revoke-a-sas, it's possible to revoke SAS tokens by rotating or regenerating the storage account access key.

**Comment by timja** [comment]
Depending on how the file share is being used you can still use a service principal to generate a SaS on demand:
https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-user-delegation-sas-create-cli

**Comment by lemeurherve** [comment]
No progress yet, WIP on Azure Service Principal to authenticate with the Azure File Storage (as hinted in https://github.com/jenkins-infra/helpdesk/issues/3414#issuecomment-1856196680, SP can be used to generate short-term SAS token allowing access to SA)

If it's not possible then we have to confirm that SAS token can be revoked through expiration date with terraform.

**Comment by lemeurherve** [comment]
Update: I managed to generate a File Share SAS token with `az` authenticated via the service principal created in https://github.com/jenkins-infra/shared-tools/pull/131 and instantiated in https://github.com/jenkins-infra/azure/pull/557, then use it with `azcopy` to query the `updates-jenkins-io` File Share from its URL https://updatesjenkinsio.file.core.windows.net/updates-jenkins-io/

I need to change the terraform module output to get the service principal client id instead of the service principal id.

Then I'll be able to modify scripts to generate SAS token with short expiration date to use with `azcopy` instead of `blobxfer`.

**Comment by lemeurherve** [comment]
As contributors.jenkins.io is also using a File Share SAS token, I'll use it as first candidate as it's less risky/important than jenkins.io, plugins site, javadoc or the mirror scripts.

**Comment by lemeurherve** [comment]
For the record, https://github.com/jenkins-infra/azure/pull/591#issuecomment-1904459009

> SAS token revocation via its expiry date doesn't work.

**Comment by lemeurherve** [comment]
Opened https://github.com/jenkins-infra/azure/pull/595 to create a stored access policy for contributors.jenkins.io storage account that we can then pass as parameter to `az` to create the SAS token, and easily revoke it via this policy if needed.

Ref:
- https://github.com/jenkins-infra/azure/pull/595
- https://learn.microsoft.com/en-us/rest/api/storageservices/define-stored-access-policy
- https://learn.microsoft.com/en-us/azure/storage/common/storage-sas-overview#best-practices-when-using-sas

**Comment by lemeurherve** [comment]
Related:
- https://github.com/jenkins-infra/azure/issues/401

**Comment by timja** [comment]
that's a shame 😢

**Comment by lemeurherve** [comment]
Good news, it was a PEBCAK issue 😅 

I successfully generated a SAS token from a service principal and listed the content of a File Share with it.

**Comment by lemeurherve** [comment]
I need now to reproduce it as code.

**Comment by lemeurherve** [comment]
As shown in `az login --service principal` output, "<...> no credentials provided in your command and environment, we will query for account key for your storage account.", the service principal needs to have the role "Storage Account Contributor".

As seen in its description, it "lets you manage storage accounts, including accessing storage account keys which provide full access to storage account data."

**Comment by lemeurherve** [comment]
I tried several lesser important roles but `az share generate-sas token` fails with any of them.

**Comment by timja** [comment]
yeah it'll be using the storage account key I expect

**Comment by lemeurherve** [comment]
Update: contributors.jenkins.io replacement ready,
- https://github.com/jenkins-infra/contributor-spotlight/pull/78

**Comment by lemeurherve** [comment]
contributors.jenkins.io synchronized with success 🥳

**Comment by lemeurherve** [comment]
I created a shared pipeline library function to encapsulate the SAS token generation:
- https://github.com/jenkins-infra/pipeline-library/pull/839

Example of usage:
- https://github.com/jenkins-infra/contributor-spotlight/pull/97/files#diff-e6ffa5dc854b843b3ee3c3c28f8eae2f436c2df2b1ca299cca1fa5982e390cf8L103-R115

**Comment by dduportal** [comment]
Update:

- Adapt more SAS-based services to use the new token with the pipeline function (plugins.jenkins.io, jenkins.io, etc.)
- Continue install of `azcopy` and associated token generation logic (in puppet code)

**Comment by lemeurherve** [comment]
New storage account and file share with its trusted.ci.jenkins.io service principal created in https://github.com/jenkins-infra/azure/pull/623

> Looking at existing jenkins.io storage account, we noticed that most of its $70/month cost came from transactions.
Using a Premium storage account instead with no transaction cost should allow us to decrease the monthly charge.
>
> Compared to the existing "prodjenkinsio" storage account, this PR sets the new storage account replication type from "GRS" to "ZRS", sufficient for our use case.

Currently creating an initial copy manually from the existing file share to this new one.

Next step: replace blobxfer synchro by an azcopy one in https://github.com/jenkins-infra/jenkins.io/blob/master/Jenkinsfile#L89-L95

**Comment by dduportal** [comment]
> Next step: replace blobxfer synchro by an azcopy one in https://github.com/jenkins-infra/jenkins.io/blob/master/Jenkinsfile#L89-L95

In parallel :) Until the webservice is migrated

**Comment by lemeurherve** [comment]
> > Looking at existing jenkins.io storage account, we noticed that most of its $70/month cost came from transactions.
> > Using a Premium storage account instead with no transaction cost should allow us to decrease the monthly charge.
> > Compared to the existing "prodjenkinsio" storage account, this PR sets the new storage account replication type from "GRS" to "ZRS", sufficient for our use case.

Unfortunately, using a Premium storage account implies a minimum size of 100Gio for file shares, corresponding to a cost of $20/month ($0.20 * 100Gio) cf https://azure.microsoft.com/en-us/pricing/details/storage/files/#pricing

![image](https://github.com/jenkins-infra/helpdesk/assets/91831478/77f3e3e1-1c01-4a2f-b562-e477e66558ad)

In regard to this new information, we'll proceed to the file shares migration to Premium only if their cost is above $20 per month.

**Comment by lemeurherve** [comment]
Also, it seems that GRS isn't available in Premium:

<img width="1035" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91831478/acb15581-9dd8-4fa5-ae36-94d7a49bdb04">

**Comment by lemeurherve** [comment]
After updating jenkins.io helm chart to allow specifying different storage accounts depending on the version (international or chinese) and to fix some resource name references, jenkins.io has been migrated to its new `jenkinsio` storage account, without any service disruption.

I'll do a cleanup at the end of this help desk.

**Comment by lemeurherve** [comment]
Next step: do the same with https://github.com/jenkins-infra/plugin-site

Its current storage account `prodpluginsite` costs around $70/month (similar to jenkins.io previous storage account cost):
<img width="516" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91831478/af866bc7-421a-4cf2-87d2-0e7f90ccac04">

- [ ] plugin-site
  - [ ] Create Premium `pluginsite` storage account, File Share and service principal (infra.ci.jenkins.io)
  - [ ] Create AzureServiceprincipal credentials on infra.ci.jenkins.io
  - [ ] Use `azcopy` to upload generated content to the new storage in parallel (*)
  - [ ] Update plugin-site release to use the newly populated storage
  - [ ] Remove `blobxfer` related elements

**Comment by lemeurherve** [comment]
### javadoc

Same case as previously, its current storage account is costing around $50/month and can benefits from a migration to a Premium storage account:
<img width="445" alt="image" src="https://github.com/jenkins-infra/helpdesk/assets/91831478/ecbdbf28-9df5-4313-833c-9dd7168ebf33">

- [ ] javadoc
  - [ ] Create Premium `javadoc` storage account, File Share and service principal (trusted.ci.jenkins.io)
  - [ ] Create AzureServiceprincipal credentials on trusted.ci.jenkins.io
  - [ ] Use `azcopy` to upload generated content to the new storage in parallel
  - [ ] Update `javadoc` release to use the newly populated storage
  - [ ] Remove `blobxfer` related elements

**Comment by lemeurherve** [comment]
As noted in https://github.com/jenkins-infra/helpdesk/issues/3968#issuecomment-1973814916 we also need to replace any current long lived SAS tokens by short lived ones:
- https://github.com/jenkins-infra/crawler/blob/d2dab62210dacd15441d09a986f088020e7babeb/Jenkinsfile#L73

**Comment by lemeurherve** [comment]
> As noted in [#3968 (comment)](https://github.com/jenkins-infra/helpdesk/issues/3968#issuecomment-1973814916) we also need to replace any current long lived SAS tokens by short lived ones:
> 
>   * https://github.com/jenkins-infra/crawler/blob/d2dab62210dacd15441d09a986f088020e7babeb/Jenkinsfile#L73

Addressed in https://github.com/jenkins-infra/crawler/pull/144

**Comment by lemeurherve** [comment]
The last remaining repository using blobxfer is https://github.com/jenkins-infra/mirror-scripts/.

This repo contains scripts cloned in pkg.origin.jenkins.io VM and used to synchronize update-center data and Jenkins mirrors.

Opening a status to update these scripts this afternoon.

**Comment by dduportal** [comment]
Update about the operation to replace `blobxfer` on `pkg.origin.jenkins.io` VM:

- https://github.com/jenkins-infra/mirror-scripts/pull/14 was not delivered until the operation and caused script failures. Fixed with the following hotfix changes:
    - https://github.com/jenkins-infra/mirror-scripts/commit/600a7c5434202fb6e20cdd4f3816b868079e682f
    - https://github.com/jenkins-infra/mirror-scripts/commit/257bef5b9df35ec0bf3397df465a02ff9fc4e613 
- https://github.com/jenkins-infra/mirror-scripts/pull/15 introduced a minor issue around the `azcopy` flags. Fixed with https://github.com/jenkins-infra/mirror-scripts/commit/a11ce239f3cc87c7bb13563d61a0d60c44222fe0
- https://github.com/jenkins-infra/mirror-scripts/pull/13 was not delivered prior to this operation and caused issues as the `www-data` user running the `sync*.sh` scripts did not had the correct `archives` SSH private key in its `$HOME/.ssh` directory. Fixed **temporarily** by adding the proper SSH key for the `www-data` from the `mirrorbrain` user.

----

We had a bad surprise during the operation: as `azcopy` MD5 mode with "Hiddenfile" (`--local-hash-storage-mode=HiddenFiles`) creates 1 hidden file for each file, we started to drown the VM under I/Os (and the mirror transfers as more than 12k files were created and had to be transferred trhough either `rsync` or `azcopy`).

Trying to [switch to `user_xattr`](https://github.com/jenkins-infra/mirror-scripts/pull/17) (as the disk is a standard ext4 with `xattr` support) to have better performances, we realized that the jenkins-infra/mirrorscripts can be run by **distinct** users on the VM (`www-data` from any trusted.ci jobs and `mirrorsync` for the full sync) which creates a LOT of concurrent access => this made the xattr to fail as the owner of files changes over time.

----

We decided to unify the permissions and ownership on the VM (tested manually)

- Owner should be `mirrorbrain` with read and write
  - External system such as trusted.ci should use `mirrorbrain` as SSH and Rsync user: https://github.com/jenkins-infra/update-center2/pull/770
- Group should be `www-data` with read only access, to allow `httpd` (apache2) to serve files without any risk of tampering data

Required to change `rsync` calls (removing the `-g` and `-o` options from the `-a` and explicitly set ownership with `--chown` as we use rsync 3.1.x+ everywhere):

- mirror-scripts: https://github.com/jenkins-infra/mirror-scripts/pull/18/files
- update-center2: https://github.com/jenkins-infra/update-center2/pull/771/files

Then, we set up the permissions on the `pkg` VM:

```
cd /srv/releases/jenkins
# -h to avoid dereferencing links
# Usage of 'find' is more efficient than recursive chown/chmod
find . -exec chown -h mirrorbrain:www-data
find . -type f -exec chmod 640 {} \;
find . -type l -exec chmod 640 {} \;
find . -type d -exec chmod 750 {} \;

# Repeat on /var/www
```

=> It did work BUT it broke OSUOSL: success in sending data to them, BUT their Apache2 and Rsync services always answered "403 Forbidden".
=> Which also broke archives.jenkins.io content updates (service up, serving data prior to the operation but not updated)

**Comment by dduportal** [comment]
Update:

> ```
> cd /srv/releases/jenkins
> # -h to avoid dereferencing links
> # Usage of 'find' is more efficient than recursive chown/chmod
> find . -exec chown -h mirrorbrain:www-data
> find . -type f -exec chmod 640 {} \;
> find . -type l -exec chmod 640 {} \;
> find . -type d -exec chmod 750 {} \;
> 
> # Repeat on /var/www
> ```
> 
> => It did work BUT it broke OSUOSL: success in sending data to them, BUT their Apache2 and Rsync services always answered "403 Forbidden". => Which also broke archives.jenkins.io content updates (service up, serving data prior to the operation but not updated)

This change was correct regarding ownership, but OSUOSL support team told us (as per our request by mail) that the permissions for "others" should be read-only (instead of "no access" in the setup above) to allow apache2 and rsync to read files (and serve them).

=> we could think about such a setup (and let mirrorbrain own everything) but for now, [setting file/link permissions to `644` and directories to `755`](https://github.com/jenkins-infra/mirror-scripts/commit/cf71e0c5f6c49aba63192f487a3457121919f60e) on both scripts and `pkg` VM solved the issue (along the HUGE help from OSUOSL whom fixed all permissions on their systems before we even understood the issue: thanks!).

- OSUOSL is now up and running. It might take a few hours before the mirrors are running again
- archives.jenkins.io is also syncrhonizing again.

**However** we see really bad performances with `azcopy`, storage and we have some config as code persistence to do:

- update-center uses it with "time based" comparison and the whole build is around 5 min and 15s which is way above what we expect.
- The "full" sync takes more than 30 min which ends in the Azure token expiring. It is using MD5 with xattr.
- azcopy generates a LOT of logs in `/srv/releases/.azcopy`: we need to purge this data one way of another (less logs? clean up ?)
- Persist permissions sets in Puppet (https://github.com/jenkins-infra/jenkins-infra/pull/3348)
- Remove blobxfer from everywhere (including puppet)
- Retrieve mirror-scripts into puppet (new compelling reason: templating these scripts with the permissions and ownership)

**Comment by dduportal** [comment]
Additionally:

- jenkins-infra/crawler required to update the ssh/rsync user (like update-center): https://github.com/jenkins-infra/crawler/commit/2660c76dd00b0ba3bc3070695ea60c9059100c22
- We **must** search and check how is the core/package process handling the copy to the remote pkg (jenkins-infra/release and jenkinsci/packaging)

**Comment by dduportal** [comment]
Update:

- One of the numerous `azcopy` we are running seems to flatten directory hiearchy as per https://github.com/jenkins-infra/helpdesk/issues/4013 
- OSUOSL is back (Apache/rsync) but still not visible on the get.jenkins.io mirrors: we have to check the scanning messages (and enable it if needed)

**Comment by dduportal** [comment]
Update:

Everything should be working as usual now. We keep the status.jenkins.io issue opened for the next 24h to ensure we don't have unexpected behaviors.

What did we do:

> update-center uses it with "time based" comparison and the whole build is around 5 min and 15s which is way above what we expect.

[Switching to `azcopy copy` with time-based comparison](https://github.com/jenkins-infra/mirror-scripts/pull/23) decreased the impact of the copy to get.jenkins.io: jenkins-infra/update-center2 execution baseline is now under the 5 min threshold (4min15 to 4min45 on the past builds)

> The "full" sync takes more than 30 min which ends in the Azure token expiring. It is using MD5 with xattr.

[Switching to `azcopy copy` with time-based comparison](https://github.com/jenkins-infra/mirror-scripts/pull/23) had the same performance effect. We see the "full sync" taking 2 min up to 5 min. Drastic improvement.

> azcopy generates a LOT of logs in /srv/releases/.azcopy: we need to purge this data one way of another (less logs? clean up ?)

Solved by decreasing the scanning logs produced by `azcopy` operations (see https://github.com/jenkins-infra/mirror-scripts/pull/22 and https://github.com/jenkins-infra/mirror-scripts/pull/23), along with introducing a regular cleanup (https://github.com/jenkins-infra/mirror-scripts/pull/19)

> Persist permissions sets in Puppet 

- See https://github.com/jenkins-infra/jenkins-infra/pull/3348
- Verified after 6 hours by searching for remaining files owned by `www-data` in both `/srv/releases/jenkins` and `/var/www` => only the `www-data` .ssh directory is found as expected.

> We must search and check how is the core/package process handling the copy to the remote pkg (jenkins-infra/release and jenkinsci/packaging) 

Checked: all the "Core Release" and "Core package" processes were already using `mirrorbrain` user to connect to the `pkg` VM. As seen above, no permission issues after today's weekly Core releas 2.451.

> One of the numerous azcopy we are running seems to flatten directory hiearchy as per https://github.com/jenkins-infra/helpdesk/issues/4013

Fixed by the change to `azcopy copy` **along** with adding a trailing `/*` on the source (not working with `azcopy sync`). See https://github.com/jenkins-infra/mirror-scripts/pull/23

> OSUOSL is back (Apache/rsync) but still not visible on the get.jenkins.io mirrors: we have to check the scanning messages (and enable it if needed)

Fixed with the following set of events:

- We deleted the `mirrorbits` pods of `get.jenkins.io` one after the other, to ensure any scanning routine  stuck are killed.
- Then, for each of the configured OSUOSL mirrors, we disabled, scanned and re-enabled it:

```
# kubectl exec to a mirrorbit pod of get.jenkins.io
$ mirrorbits list # Retrieve the mirror ID
$ mirrorbits disable <mirror ID>
$ mirrorbits scan -enable <mirror ID>
```

=> after 3-4 minutes, the new core release 2.451 (which was already present since 1 hour in OSUOSL servers) was detected by mirrorbits on get.jenkins.io: https://get.jenkins.io/windows/2.451/jenkins.msi?mirrorlist

----

Next steps:

- Wait 24 hours before closing status.jenkins.io to ensure we do not miss anything
- Then, cleanup time!
  - Remove `blobxfer` from everywhere (including puppet)
  - Retrieve mirror-scripts into puppet (new compelling reason: templating these scripts with the permissions and ownership)
  - Ensure we do not provide anymore any `ssh` configuration for the `www-data` user

**Comment by dduportal** [comment]
Update:

- More errors were reported around the update center builds: https://github.com/jenkins-infra/helpdesk/issues/4016. Plugins were available on `updates.jenkins.io` but never delivered to the `get.jenkins.io` mirrorin system.
  - Issue was caused by `azcopy` [which breaks shell stdin](https://github.com/Azure/azure-storage-azcopy/issues/974) causing the loop over freshly released plugins to not run as expected. Fixed with a shell hack (see issue for details).
  - Implied improvement of observability on the `sync-recent-release.sh` script: https://github.com/jenkins-infra/mirror-scripts/commit/e04e9a0fdb1185c4856f03b3b370a827d1168aa8

- In the point above, the flag `--overwrite=` was removed causing slower `azcopy` commands. We've added it back in https://github.com/jenkins-infra/mirror-scripts/commit/a99b89cb820ea9808f5786db800670cdcd133c61 : update center builds are now averaging at ~4min30s (instead 5min).

- The TTL of the Azure Storage account used by `sync.sh` has been rolled back to `30` minutes - https://github.com/jenkins-infra/mirror-scripts/pull/24
  - We could probably decrease it as the `sync.sh` script is running in less than 30 minutes. However the benefits are low: it serves its purpose (TTL) so let's keep it like this.

- The [script `sync.sh`](https://github.com/jenkins-infra/mirror-scripts/blob/main/sync.sh) was failing to execute on the `pkg` VM when run by the crontab on the VM
  - When run interactively or by release.ci.jenkins.io (during a Core release) it works as expected and goes to completion
  - Crontab provides a different (and minimalistic) `PATH` variable than shell sessions: hotfix to include `/usr/local/bin` in https://github.com/jenkins-infra/mirror-scripts/commit/674697affcd4bb91173ef170d7b93cfc3a43af7b fixed the issue
  - Opportunity to add observability and the `azcopy` hack in `sync.sh`: https://github.com/jenkins-infra/mirror-scripts/commit/59cb5fbbc4550fe0422af26bf75733669695c09e and https://github.com/jenkins-infra/mirror-scripts/commit/9f53853755334b0d70da0431615a9dca0b4c3a4e

- It's been 24 hours without any errors reported around plugin releases, mirror synchronization (script `sync.sh`) or update_center2 updates => we're going to close the status.jenkins.io message.

Next Steps (updated after syncing with the team):

- The following Puppet changes are needed to close this issue:
    - Remove blobxfer from everywhere
    - Persist the file `/srv/releases/.azure-storage-env` (with the storage credentials, e.g. sensitive values) as it is **not** managed today

- The following Puppet changes should be done after this issue:
    - Retrieve mirror-scripts into puppet (new compelling reason: templating these scripts with the permissions and ownership) - https://github.com/jenkins-infra/jenkins-infra/issues/3352
    - Manage the `mirrorbrain` user again - https://github.com/jenkins-infra/jenkins-infra/issues/3351 (and https://github.com/jenkins-infra/helpdesk/issues/2970)
    - Finish `www-data` user cleanup - https://github.com/jenkins-infra/jenkins-infra/issues/3353

- Cleanup of SA tokens

**Comment by dduportal** [comment]
PRs for cleanup of `blobxfer` on the `pkg` VM:
- https://github.com/jenkins-infra/jenkins-infra/pull/3354
- https://github.com/jenkins-infra/mirror-scripts/pull/25

**Comment by dduportal** [comment]
> PRs for cleanup of `blobxfer` on the `pkg` VM:
> 
>     * [cleanup(pkgrepo) remove last remnants of blobxfer jenkins-infra#3354](https://github.com/jenkins-infra/jenkins-infra/pull/3354)
> 
>     * [cleanup: remove last remnants of blobxfer mirror-scripts#25](https://github.com/jenkins-infra/mirror-scripts/pull/25)

Deployed with success and ran the cleanup process. Watching update center and sync.sh

**Comment by dduportal** [comment]
> > PRs for cleanup of `blobxfer` on the `pkg` VM:
> > ```
> > * [cleanup(pkgrepo) remove last remnants of blobxfer jenkins-infra#3354](https://github.com/jenkins-infra/jenkins-infra/pull/3354)
> > 
> > * [cleanup: remove last remnants of blobxfer mirror-scripts#25](https://github.com/jenkins-infra/mirror-scripts/pull/25)
> > ```
> 
> Deployed with success and ran the cleanup process. Watching update center and sync.sh

Looks good!

**Comment by dduportal** [comment]
Managing `mirrorbrain` (crontab, user, ssh keys, etc.) user and the  `.azure-storage-env` file in https://github.com/jenkins-infra/jenkins-infra/pull/3357

**Comment by dduportal** [comment]
Update: https://github.com/jenkins-infra/jenkins-infra/pull/3357#issuecomment-2026766564 was successfully deployed.

@lemeurherve I'm handing over to you for the SA token cleanup you mentioned as I have no idea what to cleanup and this nis the last step before closing this issue.

**Comment by lemeurherve** [comment]
> @lemeurherve I'm handing over to you for the SA token cleanup you mentioned as I have no idea what to cleanup and this nis the last step before closing this issue.

Here are the last cleanup tasks remaining before we can close this issue:
- [ ] Delete `azurerm_storage_account_sas.get_jenkins_io` data & corresponding outputs: https://github.com/jenkins-infra/azure/blob/751ac5d58f4008b81ebc76f36f41611388e5bca5/get.jenkins.io.tf#L53-L95
- [ ] Delete `contributors_jenkins_io_share_url` output: https://github.com/jenkins-infra/azure/blob/751ac5d58f4008b81ebc76f36f41611388e5bca5/contributors.jenkins.io.tf#L39-L41
  - [ ] Delete corresponding `CONTRIBUTORS_JENKINS_IO_FILESHARE_SAS_QUERYSTRING` infra.ci.jenkins.io secrets in jenkins-infra/charts-secrets (private repo)
- [ ] Replace https://github.com/jenkins-infra/azure/blob/751ac5d58f4008b81ebc76f36f41611388e5bca5/infra.ci.jenkins.io.tf#L71-L99 by the use of the fileshare-sp-writer terraform module like https://github.com/jenkins-infra/azure/blob/751ac5d58f4008b81ebc76f36f41611388e5bca5/infra.ci.jenkins.io.tf#L199-L217
- [ ] Delete old `jenkinsio` file share of the `prodjenkinsio` storage account (there are two other file shares `zhjenkinsio` & `cnjenkinsio` that we must keep for now until https://github.com/jenkins-infra/helpdesk/issues/3379 is started), replaced by `jenkins-io` file share in `jenkinsio` storage account
  - [ ] Delete corresponding `BLOBXFER_STORAGEACCOUNTKEY` infra.ci.jenkins.io secrets in jenkins-infra/charts-secrets (private repo)
  - [ ] Delete corresponding `BLOBXFER_STORAGEACCOUNTKEY` credentials in trusted.ci.jenkins.io
- [ ] Delete old `prodpluginsite` storage account and its `pluginsite` file share, replaced by `pluginsjenkinsio` storage account
  - [ ] Delete corresponding `PLUGINSITE_STORAGEACCOUNTKEY` infra.ci.jenkins.io secrets in jenkins-infra/charts-secrets (private repo)
  - [ ] Delete corresponding `PLUGINSITE_STORAGEACCOUNTKEY` credentials in trusted.ci.jenkins.io
- [ ] Delete old `prodjavadoc` storage account and its `javadoc` file share, replaced by `javadocjenkinsio` storage account
  - [ ] Delete corresponding `JAVADOC_STORAGEACCOUNTKEY` credentials in trusted.ci.jenkins.io
- [ ] Remove https://github.com/jenkins-infra/crawler/blob/1e02766db7501cdf7a350e5bbcf65626173ffdc6/Jenkinsfile#L79 from jenkins-infra/crawler pipeline, unused since the removal of blobxfer
  - [ ] Delete corresponding `updates-jenkins-io-file-share-sas-token-query-string` credentials in trusted.ci.jenkins.io
- [ ] Replace `AZURE_STORAGE_ACCOUNT` by `STORAGE_NAME` in jenkins-infra/jenkins-infra:
  - https://github.com/jenkins-infra/jenkins-infra/blob/02bb2ba3b8bef207c92a5b573163eb53e10e92a7/dist/profile/manifests/pkgrepo.pp#L144
  - https://github.com/jenkins-infra/jenkins-infra/blob/02bb2ba3b8bef207c92a5b573163eb53e10e92a7/dist/profile/templates/mirror-scripts/sync.sh.erb#L86
  - https://github.com/jenkins-infra/jenkins-infra/blob/02bb2ba3b8bef207c92a5b573163eb53e10e92a7/dist/profile/templates/mirror-scripts/sync-recent-releases.sh.erb#L19

**Comment by lemeurherve** [comment]
blobxfer completely replaced by azcopy, cleanup done, all concerned jobs green, closing this issue.
