### ISSUE TITLE
`jenkins/inbound-agent` is deprecated in favor of `jenkins/inbound-agent` ?

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3445]
### Service(s)

Docker Hub

### Summary

According to the description, https://hub.docker.com/r/jenkins/inbound-agent is deprecated in favor of https://hub.docker.com/r/jenkins/inbound-agent, kind of confusing.

I'd take a guess and assume this is just bad copy/paste from https://hub.docker.com/r/jenkins/jnlp-slave, no?

Do we have auto-builds setup to sync readme content? If so, I can file a PR to get it sorted. Otherwise, I'd like to ask someone else to take care of it, please.

Thanks!

**Comment by dduportal** [comment]
Hello @NotMyFault could you help me in this change?

I'm currently looking at https://hub.docker.com/r/jenkins/inbound-agent and I'm not sure what is expected?

If it is ok for you, could you send a PR to https://github.com/jenkinsci/docker-inbound-agent/blob/master/README.md (which is the same content) and we'll see how to update it on the DockerHub?


As per the "automatic update of the description on DockerHub from GitHub's README", it used to only be available with auto-builds (e.g. DockerHub taking care of building/publishing the image) which is not wanted for Jenkins images (we build images and push them as we want to control the process).
Since it is automated, we use PAT for authenticating to DockerHub: for the past 3 years, using PAT did not allow to update description through the DockerHub API.
But it recently changed: https://github.com/docker/hub-feedback/issues/1927 so we should be able to automate it \o/

**Comment by NotMyFault** [comment]
> and I'm not sure what is expected?

Have the links of [jenkinsci/jnlp-slave](https://hub.docker.com/r/jenkinsci/jnlp-slave/) and [jenkins/jnlp-slave](https://hub.docker.com/r/jenkins/jnlp-slave/) been updated already?
I swear I believe they linked to the same page 🤔 

Anyway, my concerns have disappeared in thin air. No further action needed, I guess 👏
