### ISSUE TITLE
agent instability

### ISSUE THREAD

**Issue by jtnord** [jenkins-infra/helpdesk#3451]
### Service(s)

ci.jenkins.io

### Summary

I have had several builds of a PR fail as the agent disconnected (and did not come back).

e.g. https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fmaven-hpi-plugin/detail/PR-449/4/pipeline/34

I have suspicions that this is due to the agent process being OOMKilled (but they are just suspicions[1]) and that the agent is killed rather than the maven process or its tests. 

Whilst if true, this is a fault with the code being built not constraining its JVM so it behaves differently on different platforms, having the agent killed over a launched process is sub optimal because as a user I can not see the memory issue.  (if surefire or the like was killed I would generally see an exit code of `137`)

Would it be possible in the agents (not sure how they are all launched etc..) to configure the process to be less likely OOMKilled, either by disallowing over commit of memory in the linux kernel or adjusting[2] the `oom_score` for the `agent.jar` (requires root).

I am assuming (🤞) that the `agent.jar` process itself is already using suitable jvm arguments such that it is not itself the hog.

[1] It appears as though neither the build nor the invoker tests constrain maven
[2] https://www.percona.com/blog/out-of-memory-killer-or-savior/

### Reproduction steps

1. use ci.jenkion.io infra and spaw processes that use memory and output some logs
2. while agent alive not dead - goto 1 and use more processes and memory_

**Comment by jtnord** [comment]
probably not possible if these are k8s pods rather than some spot type instance, as they are already adapted by k8s (depending on `requests` and `limits`), but someone with some more internals may be able to say otherwise.

**Comment by dduportal** [comment]
This build definitively used containers (in this case: an AWS EKS cluster : the `mvn version` reports `OS name: "linux", version: "5.10.165-143.735.amzn2.x86_64", arch: "amd64", family: "unix"` => on AWS we use either Ubuntu based-VM agents or EKS Linux containers.

I agree with you : since we have not seen a `137` exit code + the AWS monitoring does not report any OOM kill: this was definitively not an OOM.

It looks likely related to https://github.com/jenkins-infra/helpdesk/issues/3423: the instabilities created by the bunch of BOM builds ending in filling the EKS cluster VMs disks coincide with the timeline of your problem: we cannot confirm but gut feeling there.

Have you seen any other builds with the behavior though?

Another thing ot check: since we use spots instances, that can reclaimed, we shall see if AWS report that spot instances were reclaimed in that time windows.
