### ISSUE TITLE
forgot jenkins login password

### ISSUE THREAD

**Issue by Shantanu10101** [jenkins-infra/helpdesk#3454]
### Type(s) of account issue

I've lost my password

### Summary

forgot jenkins login password

### jenkins.io account username

shantanu_10

### jenkins.io account email

sam.61218@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
Hi @Shantanu10101 , it does not seem you have an account on accounts.jenkins.io at all.

accounts.jenkins.io is only for accessing the issues.jenkins.io website (or for Jenkins plugin maintainers).

I'm closing this issue because either:

- If you really need to have an account on the Jenkins issue tracker then create your account and your problem is solved.
- Or contact your Jenkins administrors (which are not here).
