### ISSUE TITLE
Move `awestruct-ibeams` into `jenkins.io` repository

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#3455]
### Service(s)

jenkins.io

### Summary

As noted in https://github.com/jenkins-infra/awestruct-ibeams/issues/16 and reproduced it for greater exposure and potential opinion gathering,

> I guess this repo won't have any updates anymore -- in case any changes are needed here, the code should be just moved to jenkins.io repo to simlify the workflow.

_Originally posted by @zbynek in https://github.com/jenkins-infra/awestruct-ibeams/issues/15#issuecomment-1464593210_

**Comment by zbynek** [comment]
The pcakage provides 3 beams:
* datadir - already copied to awestruct, no need to move
* asciidoc sections - can be moved to jenkins.io
* debuggable partial - maybe can be moved to awestruct too

Note that there are also plans to move the whole website away from awestruct as art of this years GSoC, so this issue is only relevant if there is a need to change something in the ibeams before the migration is done.

**Comment by zbynek** [comment]
@lemeurherve can you please archive the ibeams repository?

**Comment by lemeurherve** [comment]
@zbynek archived, thanks for the inlining!
