### ISSUE TITLE
Password reset email not coming through

### ISSUE THREAD

**Issue by sg-sehattersley** [jenkins-infra/helpdesk#3478]
### Type(s) of account issue

I didn't receive any email

### Summary

I signed up for Jenkins Jira but I never got an email with my initial password. I then tried the password reset but also did not get an email. I tried creating my account again but it wont let me as the username is already in use.

### jenkins.io account username

stehat

### Which URL are you trying to login at?

[account.jenkins.io/passwordReset](https://accounts.jenkins.io/passwordReset)

**Comment by dduportal** [comment]
Hi @sg-sehattersley , I've just reset your password from the administrative dashboard.

Assuming your organization grey-listed the jenkins.io domain, it should have triggered (more than 1 hour before 2 tentatives) email transmission: did you receive it?

Otherwise we'll have to check our SMTP servers.

**Comment by sg-sehattersley** [comment]
No nothing has come though. Checked my jumk folder as well.

**Comment by sg-sehattersley** [comment]
Just poping out for a bit so will check my emails when I get back.

**Comment by dduportal** [comment]
Thanks for checking.

- Just created a new dummy account and I received the email (went to a Gmail IMAP server): the email are sent by the application.
- We're going to check the SMT servers on our side (might take some time) to see if our SMTP are signaling an issue with mailbox.org (the mail server behind your hattersleyhome.com domain). Please note that it might takes some time.

If you need an account urgently, please create a new one with another email domain.
Otherwise we'll let you know as soon as we'll have checked the SMTP.

**Comment by sg-sehattersley** [comment]
Amazing thank you

**Comment by dduportal** [comment]
Hi @sg-sehattersley , we are not able to check the email sending logs as for now. We are working on this but it can take some times (1-2 weeks).


If you need a Jenkins account until then, may I suggest to use another email domain temporarly (you will be able to change it back to this email later)?

Sorry for the inconvenience, and thanks for your patience

**Comment by dduportal** [comment]
Hi @sg-sehattersley , thanks for your patience.

We are having trouble accessing the email sending system, which forces us to switch to another provider to ensure we can monitor email sending.

It might need a couple of days since the person in charge of this is in PTO.

Thanks for your patience!

**Comment by dduportal** [comment]
Ping @lemeurherve , attributing the issue to you, you should be ready to start working on migrating accountapp from sendgrid to mailgun 👍

**Comment by sg-sehattersley** [comment]
Sounds like a can of worms has been uncovered. Sorry!

**Comment by dduportal** [comment]
> Sounds like a can of worms has been uncovered. Sorry!

Don't be, it is really inconvenient for end users so better to spend some time on improving the service!

**Comment by dduportal** [comment]
Hi @sg-sehattersley , quick update: we are tracking the work in https://github.com/jenkins-infra/helpdesk/issues/3534 and we wil llet you know when the email provider will be switched and set up, so you can retry.

**Comment by lemeurherve** [comment]
Hi @sg-sehattersley, I've changed the mail provider and sent you a password reset mail, seen as "delivered" in the logs.

Could you check if you received it please?

**Comment by sg-sehattersley** [comment]
@lemeurherve 
I have recieved the email.
The link in the email did not work but I got around it by going to the website and resetting my password from there using the forgot password.

I can now confirm I have access to the Jenkins Jira.


Thank you so much for fixing this!

**Comment by lemeurherve** [comment]
Great, thanks for confirming!
