### ISSUE TITLE
Update center is missing Jenkins 2.403 weekly release

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#3556]
### Service(s)

Update center

### Summary

The Jenkins update center has not yet detected the release of Jenkins 2.403. https://updates.jenkins.io/latest/jenkins.war?mirrorlist shows that the update center believes that Jenkins 2.402 is the most recent release of Jenkins weekly.

I believe this is due to the safety measure in the update center certificate expiration check that is causing update center jobs to fail.

### Reproduction steps

1. Open https://updates.jenkins.io/latest/jenkins.war?mirrorlist and confirm that Jenkins 2.402 is shown rather than 2.403

**Comment by dduportal** [comment]
Thanks for catching this!

As per https://github.com/jenkins-infra/helpdesk/issues/3489#issuecomment-1531757926, that should now be fixed since ~10 min roughly. 

I see the link of this issue to be redirected to 2.403 now (while it was not before fixing the update center job). 

Is it the same for you?

**Comment by MarkEWaite** [comment]
Confirmed that the update center is showing the 2.403 release.  Thanks very much!
