### ISSUE TITLE
Jacked plugin is not visible on https://plugins.jenkins.io/

### ISSUE THREAD

**Issue by sairen-carbonetes** [jenkins-infra/helpdesk#3563]
### Service(s)

plugins.jenkins.io

### Summary

Hi, I have a problem, I expected the plugin to be visible on https://plugins.jenkins.io/. I already published my code on Jenkins and created a release but it's not visible on https://plugins.jenkins.io/. 

Here's the plugin.
https://github.com/jenkinsci/jacked-plugin

Thanks for the help. 😄

**Comment by sairen-carbonetes** [comment]
Thank you @NotMyFault for helping me with this one, I will use that documentation to release my plugin. Thank you very much. 😃

**Comment by sairen-carbonetes** [comment]
Hi, after doing the Maven release. I still didn't see the jacked plugin from here https://plugins.jenkins.io/. Did I miss something? Thank you.

**Comment by sairen-carbonetes** [comment]
I already perform 2 releases to the plugin using https://www.jenkins.io/doc/developer/publishing/releasing-manually/ but I still didn't see it on https://plugins.jenkins.io/ui/search?query=jacked

**Comment by dduportal** [comment]
Diagnostics:

- There is, indeed, a valid release at https://repo.jenkins-ci.org/artifactory/releases/io/jenkins/plugins/jacked/1.2.0/
- But there isn't any git tag associated: https://github.com/jenkinsci/jacked-plugin/tags (there is a set of `v1.x.y` tags but there is no `1.2.0`)

I am now going to check the automatic Update center and the plugins.jenkins.io website, but it's worth pushing the proper tag (ideally using maven) or better: switch to CD.

**Comment by dduportal** [comment]
- The update center is referencing the jacked plugin version 1.2.0 since ~10 hours:

<img width="1440" alt="Capture d’écran 2023-05-09 à 12 47 07" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/4d018343-0834-4d2e-9ed5-0f4019258941">

- The plugins.jenkins.io website shows the Jacked plugin since ~10 hours: https://plugins.jenkins.io/jacked/

- I assume your message was written but the plugins website needed to catch the change, regenerate, deploy and un-cache it (usually it takes up to 2 hours after the successful release)



=> As the plugin has been release successfully, I'm going to close this issue. Feel free to reopen if it is not the case for you.

=> Don't hesitate to propose pull request changes to the developer documentation on jenkins.io if you feel like it could be improved to help, based on your experience on this.

Thanks for your contribution to the Jenkins ecosystem!

**Comment by sairen-carbonetes** [comment]
I'm happy because it is now reflected on https://plugins.jenkins.io/.

I have a question @dduportal:  Since there is `1.2.0` If I'm going to release a patch version or a minor version Should I use the `v1.x.y` or `1.x.y`?

I'm just concerned about how am I going to write a version when I release a new version. Thank you

**Comment by dduportal** [comment]
> I'm happy because it is now reflected on https://plugins.jenkins.io/.
> 
> I have a question @dduportal: Since there is `1.2.0` If I'm going to release a patch version or a minor version Should I use the `v1.x.y` or `1.x.y`?
> 
> I'm just concerned about how am I going to write a version when I release a new version. Thank you

- If you wish to use use [Semantic versioning](https://semver.org), then you should drop the `v`: https://semver.org/#is-v123-a-semantic-version to ensure coherency between git tags, GitHub releases, Maven releases, Update Center indexes and plugins.jenkins.io generated documentation

- You could switch to the "JEP-305" default version scheme https://github.com/jenkinsci/jep/tree/master/jep/305#basic-usage which is used as default for the "Plugins Continuous Delivery" process as per https://github.com/jenkinsci/jep/blob/master/jep/229/README.adoc#version-format => most of the plugins are using this. It's compliant with semver though (with the commit id as semantic metadata as suffix)

**Comment by sairen-carbonetes** [comment]
Thank you.  I'll stick with the semantic version when I release it.
