### ISSUE TITLE
weekly.jenkins.io migration fixups

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3583]
> weekly.jenkins.io migrated:

_Originally posted by @lemeurherve in https://github.com/jenkins-infra/helpdesk/issues/3351#issuecomment-1546026790_

---

This migration left weekly.ci in a bad state (all jobs gone, broken header). I went ahead and restored the jobs and setting:
- https://github.com/jenkins-infra/kubernetes-management/pull/3933
- https://github.com/jenkins-infra/kubernetes-management/pull/3934
- https://github.com/jenkins-infra/kubernetes-management/pull/3935

weekly.ci is (almost) in good shape again, but https://weekly.ci.jenkins.io/job/folder/job/freestyle/ doesn't build because there are no executors available (yet)?

**Comment by lemeurherve** [comment]
Thanks for these PRs @NotMyFault !

About the markup formatter: at first the HTML wasn't rendered for the intro text, then as soon as we restored the connection between LDAP & weekly.ci.jenkins.io it was correctly rendered.
We assumed the fact the controller wasn't able to contact LDAP was the reason the HTML wasn't rendered, but since you had to fix it as code in a PR seems to contradict that.

> there are no executors available

This is intentional on weekly.ci.jenkins.io, removing executor increase the security of this instance, intended as a demo only.

I'm not convinced we should add executors just for running a freestyle job example but I could be wrong.

**Comment by NotMyFault** [comment]
> I'm not convinced we should add executors just for running a freestyle job example but I could be wrong.

Yeah, we don't need them there. weekly.ci looks looks fine again. I think we can close this ticket and remove the old instance.

**Comment by dduportal** [comment]
For the record, I set up the controller (manually, in the UI) to have 2 executors, ran the pipelines, and finally restored it back to zero.

+1 with @lemeurherve : we should not had any executor (to avoid having *any* credential at all).

Thanks for the PRs and the work folks! I'm closing the issue.
