### ISSUE TITLE
"Set me up" does no longer generate encrypted password xml

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3589]
### Service(s)

Artifactory

### Summary

Walking through Artifactory's "Set me up" part, used to download a .xml with your encrypted accounts.j.io password, used for deployments from your machine.
I've changed my password some time ago, but redoing the "Set me up" part doesn't generate a new .xml with the updated password.
What am I supposed to do in this case?

**Comment by NotMyFault** [comment]
Worked my way around via `curl -u notmyfault:pw https://repo.jenkins-ci.org/setup/settings.xml`

**Comment by MarkEWaite** [comment]
We've included this behavior change as a meeting topic for a session with have with JFrog later this week.  We've been working to reduce the bandwidth used by https://repo.jenkins-ci.org and feel like we can ask them this question at the same time, since we may need to use authenticated access to https://repo.jenkins-ci.org  much more in the future.

**Comment by dduportal** [comment]
For info, tracked in https://github.com/jenkins-infra/jenkins.io/issues/6373 for the developers
