### ISSUE TITLE
Remove IP restriction on bounce or migrate to VPN

### ISSUE THREAD

**Issue by timja** [jenkins-infra/helpdesk#3624]
### Service(s)

trusted.ci.jenkins.io

### Summary

It was agreed that the IP restrictions would be lifted after the initial migration,
see:

https://github.com/jenkins-infra/azure/pull/334#discussion_r1179955821

Apparently it was discussed in a meeting but not in any of the issues:
https://github.com/jenkins-infra/documentation/blob/main/meetings/2023-06-13.md?plain=1#L52

see also:
https://github.com/jenkins-infra/azure/pull/409

Please either remove the restrictions or migrate trusted access to VPN (preferred)

(A step further could be something like AzureAD Application Proxy which is even nicer then no VPN required)

**Comment by dduportal** [comment]
> Apparently it was discussed in a meeting but not in any of the issues:

Absolutely. We did not have enough time since the discussion and now to write down the informations there.

The VPN sounds like a solution but it requires carefull set up as trusted as always meant to be on a separated network:
- Either we use the current "private" VPN (less setup for users, but need carefull network initial build-up to not overlap while peering + a bit of puppet)
- Or we can set up a VPN instead of the SSH bastion



> (A step further could be something like AzureAD Application Proxy which is even nicer then no VPN required)

Yes, we considered it (you suggested it some time ago) but it would required creating yet another user referential (in addition to the VPN+LDAP or puppet/Linux user base).

**Comment by dduportal** [comment]
Short term: lifting restrictions in https://github.com/jenkins-infra/azure/pull/410

**Comment by dduportal** [comment]
Switching to VPN to have another layer of security (instead of IP allow listà) would need the following steps:

- Peer the private-vnet to trusted-vnet (be carefull for the IP overlaps)
- VPN:
  - Update the routing table of the VPN ccd files for users allowed to reach trusted-vnet
  - Update the VM routing table to add the peered network (like we already do for private -> public)
- Update the trusted-vnet NSG for inbound SSH to only VPN's VM IP

**Comment by dduportal** [comment]
Starting work on this topic, following the same pattern as what we did for cert.ci:

- [ ] Network peering (private <-> trusted) in azure-net
- [ ] Setting up routing in the VPN but only on the SSH bounce bastion VM IP (`/32`) in puppet
- [ ] Adding routing to CCDs to docker-openvpn (+ deploy new image)
- [ ] Update trusted.ci NSGs to restrict from VPN

**Comment by dduportal** [comment]
It's done 👍
