### ISSUE TITLE
reset passwd mail

### ISSUE THREAD

**Issue by ganeshlagudu** [jenkins-infra/helpdesk#3632]
### Problem with this page

[Email sent! | Jenkins](https://accounts.jenkins.io/resetMail) page

### Expected behavior

when i was enertered to login to the jenkins.it shows invalid .

### Actual behavior

jenkins login problem

### Possible solution

reset passwd possible solution

**Comment by dduportal** [comment]
Hi @ganeshlagudu , it looks like your are mixing your Jenkins's organization account with the public jenkins.io's account management, which are unrelated.

If you really want to access the public "ci.jenkins.io" (because you would be a Jenkins contributor) then you can reset your password with accounts.jenkins.io public page.
Otherwise, you'll have to contact the administrators of your organization (as the issue trackers here are for the *.jenkins.io websites only).
