### ISSUE TITLE
Cannot log into JFrog Artifactory anymore

### ISSUE THREAD

**Issue by uhafner** [jenkins-infra/helpdesk#3680]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

I cannot log into JFrog Artifactory anymore: 

```
Login has failed. Due to Incorrect username/password or locked user.
```

I can log into Jira and accounts.jenkins.io though. 

### jenkins.io account username

drulli

### jenkins.io account email

ullrich.hafner@gmail.com

### Which URL are you trying to login at?

https://repo.jenkins-ci.org/ui/login/

**Comment by uhafner** [comment]
BTW: it would make sense to link https://github.com/jenkins-infra/helpdesk somewhere prominent at the jenkins.io site, or do I missed this link?

**Comment by dduportal** [comment]
Hello @uhafner , your Artifactory account, despite being stored in LDAP, had a legacy setup in Artifactory.

I've manually changed the setup as Artifactory admin by enabling the "Disable internal password" to force usage of the LDAP password instead of the Artifactory's internal database.

Can you retry if it works now with your LDAP username + password?


NB: the last successful login was in 2020, I guess it explains why the legacy setting was present.

**Comment by dduportal** [comment]
For Artifactory admins:

<img width="519" alt="Capture d’écran 2023-07-26 à 14 31 14" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/f2ba0b2a-ae4e-4c5f-809b-0a4e1305d415">

**Comment by uhafner** [comment]
Login works now, thanks. Actually I don't use a login there. A release upgrade failed due to a 401 so I wanted to see why the upload of the artifacts did not work.

**Comment by dduportal** [comment]
Cool, thanks for the confirmation!

I'm closing the issue then. Feel free to reopen if needed.

FYI: https://github.com/jenkins-infra/jenkins.io/issues/6561
