### ISSUE TITLE
401 Unauthorized on repo.jenkins-ci.org

### ISSUE THREAD

**Issue by evernat** [jenkins-infra/helpdesk#3693]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

When releasing https://github.com/jenkinsci/monitoring-plugin with username `evernat` and password in settings.xml, I get `401 Unauthorized`

When using `curl -u evernat:mypassword https://repo.jenkins-ci.org/setup/settings.xml`, I get `401 Bad credentials`.

When trying to login as evernat in https://repo.jenkins-ci.org/ui/login/ I get `Login has failed. Due to Incorrect username/password or locked user.`

Changing password in accounts.jenkins.io changes password for issues.jenkins-ci.org but it changes nothing for repo.jenkins-ci.org in my case.

### jenkins.io account username

evernat

### jenkins.io account email

evernat@free.fr

### Which URL are you trying to login at?

https://repo.jenkins-ci.org/ui/login/

**Comment by dduportal** [comment]
Can you retry? I've updated the faulty setup (like in the past 4 issues this week).

Ping @daniel-beck @MarkEWaite for awareness: it looks like Jfrog rolled out a change on our Artifactory (version upgrade, configuration? I don't really now what) which makes the authentication against repo.jenkins-ci.org with username / password to try on the "local realm" instead of the "LDAP realm".

The only solution I've found so far is for each user to enable the "Disable Internal Password" (ref. https://github.com/jenkins-infra/helpdesk/issues/3680#issuecomment-1651716208) to force authentication to rely on LDAP for the password.

=> Only Artifactory admins can do this change so I guess I'm the bus factor for now
=> It looks like I might have to run a batch on the users using their [REST API](https://jfrog.com/help/r/jfrog-rest-apis/update-a-user-partial-update) to enforce `internal_password_disabled` to `true` on all user accounts with the `realm` atrtribute containing `ldap`.

**Comment by evernat** [comment]
It works now and https://github.com/jenkinsci/monitoring-plugin is released. The issue is fixed.
Merci
