### ISSUE TITLE
I am unable to login to issues.jenkins.io and can't reset my password (email never arrives)

### ISSUE THREAD

**Issue by bnfbiz** [jenkins-infra/helpdesk#3695]
### Type(s) of account issue

I didn't receive any email

### Summary

Unable to login to my account and unable to reset my password (the email never arrives)

### jenkins.io account username

blf

### jenkins.io account email

brianrobotics@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset
issues.jenkins.io

**Comment by dduportal** [comment]
Hi Brian,
your user account was locked due to a platform incident from 2021.

There was no email associated to your account in the LDAP (marker of locked account since the incident).

Given that https://issues.jenkins.io/secure/admin/user/ViewUser.jspa?atl_token=B5BF-G2S8-8N2K-SZ3R_d636e2c89f9f8919c8b98d34196b21f90ce318be_lin&name=blf confirms the provided email is good, so you're not taking over, I've set up your email to the proper value and sent a reset of the password.

You should receieve it soon: can you confirm?

**Comment by bnfbiz** [comment]
yes that worked great. Thanks!
