### ISSUE TITLE
Not able to login to artifactory

### ISSUE THREAD

**Issue by swamy-m-s** [jenkins-infra/helpdesk#3702]
### Service(s)

Artifactory

### Summary

Even after providing right credentials, I am not able to login to artifactory it says invalid creds or user blocked. Also I am not able to generate link to reset my password.

**Comment by dduportal** [comment]
Hi @swamy-m-s , the accounts used in Artifactory are delegated to the Jenkins LDAP.
It means you can manage your account using accounts.jenkins.io (instead of Artifactory): can you try logging-in in accounts.jenkins.io (or use it to reset your password) before any further attempt to log-in on Artifactory please?


Once you've ensured you have the proper credential, can you share your user account id, user email and the resaon why you plan to use Artifactory in this issue please?

We have issues with Artifcatory since the past 2 weeks (as explained in https://github.com/jenkins-infra/helpdesk/issues/3700) and I'll have to update (as Artifactory administrator) one time your user profile to allow logging-in .

**Comment by nfalco79** [comment]
I have the same issue and I can login into accounts.jenkins.io but not in artifactory this blocks my plugin releases

**Comment by dduportal** [comment]
> I have the same issue and I can login into accounts.jenkins.io but not in artifactory this blocks my plugin releases

Should be fixed for your user profile: can you check?

**Comment by dduportal** [comment]
Closing this issue as no answer from the reporter.
