### ISSUE TITLE
I cannot log into JFrog Artifactory anymore

### ISSUE THREAD

**Issue by boaglio** [jenkins-infra/helpdesk#3731]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

Login has failed. Due to Incorrect username/password or locked user.

```
$ curl -u boaglio:<MyPassword>   https://repo.jenkins-ci.org/setup/settings.xml
{
  "errors" : [ {
    "status" : 401,
    "message" : "Bad credentials"
  } ]
} 
```

I can log into Jira and accounts.jenkins.io though.

https://repo.jenkins-ci.org/ui/login/

I maintain this plugin for almost 10 years - https://github.com/jenkinsci/sqlplus-script-runner-plugin 

### jenkins.io account username

boaglio

### jenkins.io account email

boaglio@gmail.com

### Which URL are you trying to login at?

https://repo.jenkins-ci.org/ui/login/

**Comment by boaglio** [comment]
I did, still unable to login.

**Comment by MarkEWaite** [comment]
> I did, still unable to login.

You'll need to wait until an Artifactory administrator is available to apply the workaround.  It requires a command line call to change a setting in Artifactory.  Monday most likely.

**Comment by dduportal** [comment]
Hi @boaglio , thanks for raising the issue! It's caused by #3700 (a sudden change of behavior in Artifactory that we should bypass soon - e.g. the upcoming week).

I've updated your account in Artifactory with the same method as described in #3700 (as an Artifcatory admin): that should solve the issue.

Really sorry for the inconvenience it caused!

Can you confirm it work for you by closing the issue (you can wait fro your plugin release to be performed, no problem!) or commenting with the error you're having?

**Comment by boaglio** [comment]
Yes, it is working fine now, I was able to release a new version successfully. Thanks!
