### ISSUE TITLE
Akshat Tiwari

### ISSUE THREAD

**Issue by alphaviktor** [jenkins-infra/helpdesk#3764]
### Type(s) of account issue

I've been blocked by the anti-spam system

### Summary

I created an account but didnt get the password as the email was out of storage hence created new one and it recognises me as a robot.

### jenkins.io account username

alphaakshat

### jenkins.io account email

ethanfrost47@gmail.com

### Which URL are you trying to login at?

https://accounts.jenkins.io/login
![Screenshot 2023-09-27 125218](https://github.com/jenkins-infra/helpdesk/assets/103210421/80129df2-47b6-4acb-8485-d7fef421b0aa)

**Comment by MarkEWaite** [comment]
As far as I can tell from [accounts.jenkins.io](https://accounts.jenkins.io), there is no account for a user named `alphaakshat` or for an email address `ethanfrost47@gmail.com`.  Since you said:

> I created an account but didn't get the password

I think you may have misunderstood the page that was displayed.  No account has been created.  You should be able to try again with the same account name.

**Comment by MarkEWaite** [comment]
Closing after 3 days with no response
