### ISSUE TITLE
CD not working with github-release-plugin

### ISSUE THREAD

**Issue by jcustenborder** [jenkins-infra/helpdesk#3838]
### Service(s)

ci.jenkins.io

### Summary

Hello there! 

I'm having some issues getting CD to work with [github-release-plugin](https://github.com/jenkinsci/github-release-plugin). I put in a [PR to enable CD](https://github.com/jenkins-infra/repository-permissions-updater/pull/3630) and [one in the project](https://github.com/jenkinsci/github-release-plugin/pull/4/files). When I merged the PR In the project the build did not fire. Am I doing something wrong?

J

**Comment by MarkEWaite** [comment]
The ci.jenkins.io job must complete successfully before the CD process can complete.

I launched https://ci.jenkins.io/job/Plugins/job/github-release-plugin/job/main/ so that it can run to completion.  Other things may also block CD, but that is the first failure reported at https://github.com/jenkinsci/github-release-plugin/actions/runs/7022472857/job/19106822771

**Comment by MarkEWaite** [comment]
Released as [10.vc8cd6962b_e7f](http://repo.jenkins-ci.org/ui/repos/tree/General/releases/io/jenkins/plugins/github-release/10.vc8cd6962b_e7f/github-release-10.vc8cd6962b_e7f.hpi)

**Comment by jcustenborder** [comment]
Thanks @MarkEWaite! Going forward should the jenkins job fire automatically when when something is merged to main?

**Comment by MarkEWaite** [comment]
> Thanks @MarkEWaite! Going forward should the Jenkins job fire automatically when when something is merged to main?

Yes, it should.
