### ISSUE TITLE
Issues are modified by a spammer

### ISSUE THREAD

**Issue by uhafner** [jenkins-infra/helpdesk#3851]
### Service(s)

Jira

### Summary

A Spammer changed a lot of my (and possibly other?) issues:

![Bildschirmfoto 2023-12-07 um 08 37 51](https://github.com/jenkins-infra/helpdesk/assets/503338/62a43aaf-125c-46d2-97f4-30be6d81b2e4)

Example: https://issues.jenkins.io/browse/JENKINS-64358

**Comment by NotMyFault** [comment]
Same here, got more than 10 mails.

Please ban the user @jenkins-infra/jira-admins

**Comment by dduportal** [comment]
Update:

- @daniel-beck disabled the bulk update feature to avoid this case to happen again (thanks!!)
- Proposal made by @lemeurherve and @timja in the IRC channel: asking the LF to restore a backup of the data before the change and then add back other changes (need to be quick otherwise the diff to re-apply will be huge quickly)
- Ping @timja @lemeurherve @daniel-beck @MarkEWaite @NotMyFault I am not really available to drive this topic, may I ask you to check the next steps?

**Comment by NotMyFault** [comment]
I'm not in the irc channels anymore 🫠

**Comment by dduportal** [comment]
> I'm not in the irc channels anymore 🫠

My bad I meant the jenkins-infra matrix channel (force of habits)

**Comment by basil** [comment]
Rolling back sounds fine to me.

**Comment by daniel-beck** [comment]
> If they cannot, then we accept that changes since that time are lost (not an attractive choice, but I think it is a practical choice)

By now it's probably too late for this, and re-doing all changes since then will be worse than trying to restore what was vandalized.

**Comment by daniel-beck** [comment]
https://community.atlassian.com/t5/App-Central/How-to-revert-changes-made-to-the-description-of-Jira-ticket/ba-p/2403764 might work? 30 days free trial.

**Comment by timja** [comment]
that's cloud only as far as I can tell

**Comment by daniel-beck** [comment]
Are we not on Jira datacenter yet?

**Comment by MarkEWaite** [comment]
We are on Jira data center as far as I know, at least that is the license we've been granted by Atlassian.

I am working with Linux Foundation on an open ticket to identify the database backup point that precedes the Dec 6, 2023 spam point.  Eric of the Linux Foundation is checking on that.  I hope to have an answer today.

@basil noted in the governance meeting on Monday that the spammer changed the type of some issues from epic to bug and that cut the links between the epic and its children.  That makes me worry even more that we need to do the restore and accept that all changes since Dec 6, 2023 are lost.

Is that workable for the security team?

**Comment by timja** [comment]
> We are on Jira data center as far as I know, at least that is the license we've been granted by Atlassian.

Yes we are. (Single instance non clustered).

**Comment by Wadeck** [comment]
Hey there, the rollback is "OKish" for the security team. We will have to spend some time to recover the recent changes we, reporters and maintainers have applied to the security tickets.

For future occurrences, I would suggest to rollback quicker to avoid having too much manual step to do. The longer we wait, the harder it is.
That will be also a "good" test to ensure we have working backups ;)

**Comment by MarkEWaite** [comment]
> For future occurrences, I would suggest to rollback quicker to avoid having too much manual step to do. The longer we wait, the harder it is.
> That will be also a "good" test to ensure we have working backups ;)

Agreed completely that rollback sooner is much, much better.  In this case, I learned that it takes a long time to get information from our Jira administrators at the Linux Foundation.  I used an issue ticket with them when I should have escalated by email immediately.

**Comment by daniel-beck** [comment]
Please note that we'll need to know in advance before a rollback so we can save the current state of issues in the SECURITY project to allow for later manual restoration.

I also recommend someone's doing that for the 80 or so issues in JENKINS that have since been updated.

**Comment by MarkEWaite** [comment]
> Please note that we'll need to know in advance before a rollback so we can save the current state of issues in the SECURITY project to allow for later manual restoration.
> 
> I also recommend someone's doing that for the 80 or so issues in JENKINS that have since been updated.

I've scheduled the rollback with the Linux Foundation for Monday, Dec 18, 2023 beginning at 23:00 UTC.  Is that enough time for the security team to preserve the needed items?  If not, the Linux Foundation is also willing to schedule for Tuesday, Dec 18, 2023 at 23:00 UTC.

I'll send a notice to the Jenkins developers list and place an outage notice on the status page once you've confirmed the scheduled date is sufficient.

**Comment by daniel-beck** [comment]
> I've scheduled the rollback with the Linux Foundation for Monday, Dec 18, 2023 beginning at 23:00 UTC. Is that enough time for the security team to preserve the needed items?

Works for us. Can we meanwhile block access to Jira to prevent further issue updates? (I can do that for security if you'd rather keep it otherwise open.)

**Comment by MarkEWaite** [comment]
> Works for us. Can we meanwhile block access to Jira to prevent further issue updates? (I can do that for security if you'd rather keep it otherwise open.)

No objections from me if we block access to Jira.  We're intentionally discarding changes that arrive between now and the restore.  I don't know how to do that, but am happy to place a notice on status.jenkins.io that the issues.jenkins.io service is disrupted pending the restore of the backup.

**Comment by jglick** [comment]
> save the current state of issues in the SECURITY project to allow for later manual restoration.
> 
> I also recommend someone's doing that for the 80 or so issues in JENKINS that have since been updated.

What is the upshot for legitimate changes to the `JENKINS` project in the lost window? They will all be reverted by restoring from backup I guess; is anyone from infra planning to reapply them in bulk? Or is there going to be some posted list of such changes and it would be left to random people to reapply them one by one, with some way of tracking which ones are still outstanding?

I wonder if there will be a wave of projects converted to GitHub Issues in the aftermath.

**Comment by MarkEWaite** [comment]
> What is the upshot for legitimate changes to the `JENKINS` project in the lost window? 

All changes since the Dec 6, 2023 backup will be lost.  Yes, that is painful, but I think that it is less painful than the alternative of trying to undo the damage to over 1000 items.

> They will all be reverted by restoring from backup I guess; is anyone from infra planning to reapply them in bulk? 

I'm not aware of any JIRA facility that would allow us to apply changes in bulk while omitting the changes from the spammer.  If others are aware of such a facility, we're open to consider how it might be used to preserve changes since the last backup.

> Or is there going to be some posted list of such changes and it would be left to random people to reapply them one by one, with some way of tracking which ones are still outstanding?

That's a good idea that we capture a report of the issues that have been modified since the changes from the spammer so that individuals can consider if they want to reapply those changes.

**Comment by daniel-beck** [comment]
Do the admins want to do it during the night, or is that just the default of trying to not annoy users? If the latter, could do the rollback during the UTC day? That'd allow us to immediately follow up, e.g. I want to remove access to SECURITY to prevent issue creation.

**Comment by MarkEWaite** [comment]
> Do the admins want to do it at that time, or is that just the default of trying to not annoy the most users? If the latter, could do the rollback during the UTC day? That'd allow us to immediately follow up, e.g. I want to remove access to SECURITY to prevent issue creation.

I proposed UTC 23:00 as that is 3:00 PM Seattle time, assuming it would be least disruption.  Let me ask them if they are willing to move it closer to the morning Seattle time.

**Comment by MarkEWaite** [comment]
Database restore completed yesterday.  I have CSV exports of issues modified since the spam.  I may attempt to create those issues again from the CSV files, though I'm not sure when I can do that.
