### ISSUE TITLE
Did not receivve email  regarding the password

### ISSUE THREAD

**Issue by MrEnggStrange** [jenkins-infra/helpdesk#3859]
### Type(s) of account issue

I didn't receive any email

### Summary

I did not receive the email regarding the password after creating my account.

### jenkins.io account username

joejosef

### jenkins.io account email

joe.nelson@wenglor.com

### Which URL are you trying to login at?

https://issues.jenkins.io/login.jsp

**Comment by dduportal** [comment]
Hi @MrEnggStrange , it looks like your email provider at wenglor.com has grey-listed us: our SMTP server mentions the following error when trying to deliver emails to your account:

```
4.2.0 <joe.nelson@wenglor.com>: Recipient address rejected: Greylisted, see http://postgrey.schweikert.ch/help/wenglor.com.html
```

I assume we have to "wait" or you might want to contact your administrator and ask them to add us to their "allow" list in order to receive email on your domain from `@jenkins.io`.

**Comment by dduportal** [comment]
Hello @MrEnggStrange do you have any news from your email administrator please?

**Comment by dduportal** [comment]
Closing as no answer from the requester
