### ISSUE TITLE
Build PR CI check stuck for `jenkins-infra/contributor-spotlight`

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/helpdesk#3888]
### Service(s)

Helpdesk

### Summary

The Build PR check seems to be stuck at incomplete for indefinitely in https://github.com/jenkins-infra/contributor-spotlight/pull/65. 

<img width="1152" alt="Screenshot 2024-01-05 at 2 46 27 AM" src="https://github.com/jenkins-infra/helpdesk/assets/88480540/c542234c-ac2c-4404-9641-3adde0001af1">

**Comment by dduportal** [comment]
At first sight, this behavior is a consequence of the removal of the `github-autostatus` plugin (in https://github.com/jenkins-infra/helpdesk/issues/3880#issuecomment-1875108510) which was publishing each pipeline stage as a Github check by default.

We added branch protection rules relying on these checks resulting in this behavior.

Another example in https://github.com/jenkins-infra/helm-charts/pull/1003:

![Uploading Capture d’écran 2024-01-05 à 09.01.14.png…]()

**Comment by dduportal** [comment]
What to do about it:

- Short term (cc @krisstern) if the check is not marked as "Required", and all the others checks are green, it means you can proceed to merge. Next PRs (opened after the 4th January) should not have this check anymore if i'm not mistaken
- We'll have to update job configurations where we can afford punlishing steps such as jenkins-infra/contributor-spotlight
 to configure the github checks (the helm chart used for infra.ci jobs definition allows specifying custom check name along with enabling/disabling it)
- For other jobs, we'll have to either relax branch protection constraint (e.g. rmeoving the disappeared checks) are add explicit `publishCheck()` in the related pipelines

**Comment by dduportal** [comment]
- Updated the jobs configurations with https://github.com/jenkins-infra/kubernetes-management/pull/4836
- Updated branch protection rules in jenkins-infra/contributor-spotlight, jenkins-infra/kubernetes-management, jenkins-infra/helm-charts and jenkins-infra/jenkins-infra to use the new checks instead of the "disappeared" ones
- The PR https://github.com/jenkins-infra/contributor-spotlight/pull/65 was all green after these changes. Merged it (as it was approved by @krisstern).
- Updated the 2 other PRs to see the same change happening: https://github.com/jenkins-infra/contributor-spotlight/pull/44 and https://github.com/jenkins-infra/contributor-spotlight/pull/50: all checks are green now

**Comment by dduportal** [comment]
We can close this issue: note for the users of infra.ci, please reopen with details if you see other jobs with the same problem.

**Comment by dduportal** [comment]
- https://github.com/jenkins-infra/digitalocean/settings/branches updated to only require the top-level check (pr-merge) as the stages `Production` and `Staging` azre not published as GH check anymore
