### ISSUE TITLE
Help with the spam block 

### ISSUE THREAD

**Issue by Joao4ndrade** [jenkins-infra/helpdesk#3892]
### Type(s) of account issue

I've been blocked by the anti-spam system, Other (please describe in the summary below)

### Summary

I was trying do make a new account because i coundn't log in the other one i made earlier, it says that the account doesen't exist! So i tried to make a new one,  than i was blocked by the spam blocker even though i'm just tryna' work here. I need acess to schedule a job for an enterprise that i work for. Please attend.

### jenkins.io account username

joao_andrade

### jenkins.io account email

joao.andrade211@hotmail.com

### Which URL are you trying to login at?

account.jenkins.io/antispam

**Comment by MarkEWaite** [comment]
I'm not understanding why you need an account on accounts.jenkins.io in order to schedule a job for an enterprise that you work for.  The Jenkins accounts on accounts.jenkins.io control access to https://repo.jenkins-ci.org and https://issues.jenkins.io and https://ci.jenkins.io .  They do control access to accounts inside any enterprise.

Can you further explain the problem you're trying to solve by creating an account on https://accounts.jenkins.io ?

**Comment by dduportal** [comment]
Closing as no answer from the requester
