### ISSUE TITLE
Trying to signup at jenkins 

### ISSUE THREAD

**Issue by prateek1656** [jenkins-infra/helpdesk#3902]
### Type(s) of account issue

I've been blocked by the anti-spam system

### Summary

Hello Jenkins,
I was recently trying to signup on Jenkins, as i am learning automation and deployment, i am not sure why it happened or it is it a SOP, but yea that's why i am writing this

### jenkins.io account username

prateek1656

### jenkins.io account email

prateek1656@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/signup

**Comment by MarkEWaite** [comment]
Thanks for your interest in Jenkins @prateek1656 .  The Jenkins infrastructure help desk issue tracker is used for issues related to Jenkins infrastructure.  You say that you were blocked by the anti-spam system, but I see no indication that an account was created on accounts.jenkins.io.  Users need an account on accounts.jenkins.io to report issues in the Jenkins issue tracker and to release new versions of Jenkins core and Jenkins plugins.  Users don't need an account on accounts.jenkins.io to use a local installation of Jenkins.

Are you trying to use Jenkins locally or are you trying to create an account so that you can report an issue or become a Jenkins maintainer?

**Comment by dduportal** [comment]
Closing as no answer from the requester
