### ISSUE TITLE
Anti spam triggered 

### ISSUE THREAD

**Issue by WebDesys** [jenkins-infra/helpdesk#3903]
### Type(s) of account issue

I've been blocked by the anti-spam system

### Summary

hello Jenkins,
I am new to Jenkins, and trying to build automation pipelines for my team, please allow my mail through so i can continue forward

### jenkins.io account username

webdesys

### jenkins.io account email

tech@webdesys.com

### Which URL are you trying to login at?

account.jenkins.io/signup

**Comment by MarkEWaite** [comment]
Thanks for your interest in Jenkins @WebDesys .  The Jenkins infrastructure help desk issue tracker is used for issues related to Jenkins infrastructure.  You say that you were blocked by the anti-spam system, but I see no indication that an account was created on accounts.jenkins.io.  Users need an account on accounts.jenkins.io to report issues in the Jenkins issue tracker and to release new versions of Jenkins core and Jenkins plugins.  Users don't need an account on accounts.jenkins.io to use a local installation of Jenkins.

Are you trying to use Jenkins locally or are you trying to create an account so that you can report an issue or become a Jenkins maintainer?

**Comment by dduportal** [comment]
Closing as no answer from the requester
