### ISSUE TITLE
Revoke an OpenVPN cert for NotMyFault

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3906]
### Service(s)

VPN

### Summary

Hey,

Please revoke my OpenVPN certificate with the serial ID `38E3338B44444DE3504FB31651F62283`: https://github.com/jenkins-infra/docker-openvpn/blob/main/cert/pki/certs_by_serial/38E3338B44444DE3504FB31651F62283.pem

I don't use this setup to connect to the VPN and would suggest that we just get a rid of it.

Thanks!

**Comment by lemeurherve** [comment]
The easyvpn go tool we're using in https://github.com/jenkins-infra/docker-openvpn doesn't allow to revoke a certificate by its ID, only by its name.

Looking at other certs in this repo, it seems we're accumulating old certificates in `certs_by_serial` folder, but that only the last one is taken in account from the `issued` folder.

Not sure if there is anything to do here.
@dduportal can you confirm or give more more info if this assumption is wrong?

**Comment by dduportal** [comment]
Gotcha: the technique is to update manually the `index.txt` CRL database and regenerate the CRL:

- `cert/pki/index.txt` is an OpenSSL specific format with 6 fields and tabulation separator
  - First field is usually either `V` (for "valid") or set to `R` ("revoked").
  - If the first field is `R`, then the 3rd field must be set (otherwise it is empty) to the revokation date
- Once the txt file is updated, then follow the documentation for renewing the CRL as VPN admin: https://github.com/jenkins-infra/docker-openvpn?tab=readme-ov-file#howto-renew-certificate-revocation-list


Let's try the result with https://github.com/jenkins-infra/docker-openvpn/pull/333 (which should generate a new Docker image to deploy for VPN with revoked certificates)

**Comment by dduportal** [comment]
https://github.com/jenkins-infra/jenkins-infra/pull/3335 deployed, the certificate is not usable anymore
