### ISSUE TITLE
Hosting large Jenkins plugins

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/helpdesk#3925]
### Service(s)

Artifactory

### Summary

Hey,

This is more of a question than an issue, but I would like to see it clarified nonetheless.

When onboarding new plugins, the hosting team advises keeping the distributed .hpi's as small as possible, for example by depending on Jenkins plugin API's if available, such as [commons-lang3](https://plugins.jenkins.io/commons-lang3-api/) bundling the library for multiple plugins to use.

In the past, this helped us a lot to shrink the size of Jenkins plugins tremendously and save a lot of storage in artifactory and on the controller the plugin is installed on.
Sporadically, we receive a hosting request like https://github.com/jenkins-infra/repository-permissions-updater/issues/3368.
The distributed .hpi file sizes ~53M, which is considerably large for a Jenkins plugin:
<img width="543" alt="Screenshot 2024-01-29 at 14 05 03" src="https://github.com/jenkins-infra/helpdesk/assets/13383509/5cb3ce95-5545-4d17-995c-42560760cd96">
That's down to the fact that the hosting request depends on a large library they can't slim further down.

With a few plugin releases, incremental builds and incremental PR builds, hosting the plugin will drain gigabytes of storage in a short time. For comparison, a common plugin sizing ~100kb takes much longer to get remotely close to the amount of disk size the proposal would take up.

Given, we are on a sponsored plan by JFrog, and I'm not in the loop of our current disk usage (and possible limit), I would like to clarify whether we can (and should) host bigger plugins or not.

**Comment by MarkEWaite** [comment]
> Given, we are on a sponsored plan by JFrog, and I'm not in the loop of our current disk usage (and possible limit), I would like to clarify whether we can (and should) host bigger plugins or not.

Thanks for being aware of disc space on our artifact repository.  JFrog has indicated that storage costs are much less a concern than network bandwidth use.  When we met with them, we reviewed the ways that we could save on storage costs and they asked us to focus our efforts on bandwidth reduction instead.  A large plugin as in your example is OK.

I think that we should continue the existing practice of using API plugins as much as possible, because it is better for the Jenkins user (easier to update a plugin than a library that is embedded inside one or more hpi files), better for Jenkins plugin maintainers (easy to rely on a plugin and updates do not require a new plugin release), and better for storage space.

**Comment by NotMyFault** [comment]
Thanks for the swift response, Mark, and for clarifying that with JFrog. In that case, I'll go ahead and continue with the hosting process, thanks!
