### ISSUE TITLE
Commons-text API : earlier version plugin present on latest version link

### ISSUE THREAD

**Issue by NitinG0418** [jenkins-infra/helpdesk#3951]
### Service(s)

plugins.jenkins.io

### Summary

Trying to download latest version plugin for commons-text API which is 1.11.0-95.v22a_d30ee5d36. However upon installing the plugin Jenkins reporting an error that plugin version installed is 1.11.0-94.v3e1f4a_926e49

### Reproduction steps

Downloaded the latest plugin and installed it in Jenkins. Jenkins reported an error that the plugin needs to be updated.

**Comment by MarkEWaite** [comment]
Most likely a user misunderstanding because you are running an older Jenkins version than is required by the Dec 2023 release of the commons text API plugin. What version of Jenkins are you running?

https://updates.jenkins.io/latest/commons-text-api.hpi?mirrorlist shows that the Dec 2023 release of the plugin is available from multiple mirror locations.

https://plugins.jenkins.io/commons-text-api/ shows that the most recent release of the plugin requires Jenkins 2.401.3 or newer.

Downloads of that plugin version have consistently worked for me in multiple cases.  See [my plugins.txt](https://github.com/MarkEWaite/docker-lfs/blob/267063f1776ae983d95f9c5b7eaa1c7859317bfa/plugins.txt#L25) file for one example.

**Comment by NitinG0418** [comment]
Jenkins version is 2.443

**Comment by MarkEWaite** [comment]
> Jenkins version is 2.443

Then I definitely cannot duplicate the problem that you're describing.  You'll need to provide much, much more information to allow others to help you.

What do you see from your computer when you open https://updates.jenkins.io/latest/commons-text-api.hpi?mirrorlist ?  Mine looks like this:

![screencapture-get-jenkins-io-plugins-commons-text-api-1-11-0-95-v22a-d30ee5d36-commons-text-api-hpi-2024-02-14-17_03_23](https://github.com/jenkins-infra/helpdesk/assets/156685/cc0f170d-0dba-4acc-a8b5-c3d7d0cfa9ed)

What actions did you perform to download the most recent plugin release?  Were you inside a Jenkins controller or were you using a command line utility?

Please provide detailed steps so that others can duplicate the issue that you're seeing.

**Comment by NitinG0418** [comment]
[
![Uploading IMG20240215121526.jpg…]()
](url)

**Comment by NitinG0418** [comment]
I downloaded the plugin from https://updates.jenkins-ci.org/download/plugins/ as our test servers are not connected to internet. Then installed the plugin using install plugin option on the front end.

**Comment by NitinG0418** [comment]
![Uploading IMG_20240215_122537.jpg…]()

**Comment by NitinG0418** [comment]
![IMG_20240215_122537](https://github.com/jenkins-infra/helpdesk/assets/160081817/96cf0046-018c-4563-9b86-d30c881f5184)

**Comment by NitinG0418** [comment]
![IMG20240215121526](https://github.com/jenkins-infra/helpdesk/assets/160081817/76c05442-e66b-4549-9286-f37c0e1a774a)

**Comment by MarkEWaite** [comment]
> Then installed the plugin using install plugin option on the front end.

I'm closing this issue.  The issue you are having is not related to Jenkins infrastructure.

Please review ["Offline installations"](https://www.jenkins.io/doc/book/installing/offline/) for guidance on how to install and configure a collection of plugins when the Jenkins controller is not connected to the internet.  If that does not resolve your issue, then the [Jenkins community forum](https://[www](https://www.jenkins.io/doc/book/installing/offline/).jenkins.io/), the _[Jenkins chat channels](https://www.jenkins.io/chat)_, and the [Jenkins user mailing list](https://www.jenkins.io/mailing-lists) are the place to ask your questions related to offline installation
