### ISSUE TITLE
New Jenkins mirror in Romania by Hostico

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helpdesk#3976]
> We received a mail from Hostico to host a new Jenkins mirror in Romania 🎉 

_Originally posted by @lemeurherve in https://github.com/jenkins-infra/helpdesk/issues/3956#issuecomment-1972850931_

**Comment by lemeurherve** [comment]
Update: we're exchanging with them, in progress.

**Comment by dduportal** [comment]
Update: tests in progress to see how are the FTP credentials managed by mirrorbits

**Comment by dduportal** [comment]
Update:

- Mirrorbits supports username and password specification through standard inline URLS for rsync (ref. https://github.com/etix/mirrorbits/blob/e83e56ac6496a3643d18a731324bd266f75f7b32/scan/rsync.go#L43-L54) and FTP (ref. https://github.com/etix/mirrorbits/blob/e83e56ac6496a3643d18a731324bd266f75f7b32/scan/ftp.go#L56-L64)
- Tested with success on a local k3d cluster AND on a `ddu-test` distinct installation in `publick8s`: specification of user and password is done when adding the mirror:

```
mirrorbits add -rsync="rsync://username:password@host/path" -ftp="ftp://username:password@host/path" <mirror name>
```

- The provided information are not working: connection with FTP to the Hostico server fails with timeout. After an exchange with them, it appears that they removed the FTP server after a server crash as they never got any answer back from us (understandable). They'll resume the work once they are back from holidays (after 28 May) and will most probably provide an Rsync scan instead of FTP this time.

=> This issue should be quick and easy to implement once we have the informations.

**Comment by dduportal** [comment]
Update:

- Hostico asked us our public outbound IP in order to restrict their rsync server (used for mirrorbits scanning of their mirror). Just answered to them and asking what would be the procedure to update these IPs
  - I gave both publick8s and privatek8s NAT gateway public IPs from the terraform outputs of jenkins-infra/azure-net
  - Could be a nice improvement follow up of https://github.com/jenkins-infra/helpdesk/issues/3832 to publish these IPs

**Comment by timja** [comment]
Still showing as down: https://get.jenkins.io/plugins/jenkins-infra-test/166.v0b_9b_c3e0dca_1/jenkins-infra-test.hpi?mirrorlist

**Comment by timja** [comment]
(still down)

**Comment by dduportal** [comment]
Diagnosing why is it still marked as "down" in progress...

**Comment by dduportal** [comment]
First step: checking rsync connectivity from one of the mirrorbits pods:

```bash
$ rsync -v rsync://mirrors.hostico.ro/jenkins/
receiving file list ... done
drwxr-xr-x          4,096 2024/06/10 11:51:34 .
-rw-r--r--             11 2024/06/10 11:47:45 TIME
drwxr-xr-x             95 2024/03/25 15:23:01 art
drwxr-xr-x          4,096 2024/05/15 07:53:57 debian-stable
drwxr-xr-x          4,096 2024/06/04 13:25:59 debian
drwxr-xr-x          4,096 2024/05/15 07:53:54 opensuse-stable
drwxr-xr-x          4,096 2024/06/04 13:25:57 opensuse
drwxr-xr-x         73,728 2024/06/09 14:01:56 plugins
drwxr-xr-x             30 2024/03/25 15:23:01 podcast
drwxr-xr-x             27 2020/10/18 13:28:54 project
drwxr-xr-x          4,096 2024/05/15 07:53:53 redhat-stable
drwxr-xr-x          4,096 2024/06/04 13:25:57 redhat
drwxr-xr-x         12,288 2024/06/02 22:00:22 updates
drwxr-xr-x             28 2024/06/10 10:01:16 war-rc
drwxr-xr-x             28 2024/06/10 10:01:16 war-stable-rc
drwxr-xr-x            313 2024/06/10 10:01:16 war-stable
drwxr-xr-x          4,096 2024/06/10 10:01:16 war
drwxr-xr-x            313 2024/05/15 08:16:49 windows-stable
drwxr-xr-x          4,096 2024/06/04 13:45:47 windows
```

=> this one is good 👍 let's check the mirrorbits
sent 24 bytes  received 414 bytes  175.20 bytes/sec
total size is 11  speedup is 0.03
```

**Comment by dduportal** [comment]
Weird: the logs from the mirrorbits system shows that the rsync repository is scanned with success:

```
Indexed 40077 files (40072 known), 0 removed
```

but the mirror still shows as "down" in the CLI output:

```
mirrorbits list       
Identifier                      STATE           SINCE
mirrors.tuna.tsinghua.edu.cn    up              (Fri, 07 Jun 2024 08:59:02 UTC)
mirror.xmission.org             up              (Fri, 07 Jun 2024 02:02:33 UTC)
mirror.freedif.org              up              (Thu, 06 Jun 2024 12:35:53 UTC)
ftp.yz.yamagata-u.ac.jp         up              (Fri, 31 May 2024 07:08:32 UTC)
ftp.belnet.be                   up              (Mon, 27 May 2024 00:01:09 UTC)
ftp.halifax.rwth-aachen.de      up              (Sat, 25 May 2024 20:26:57 UTC)
ftp-chi.osuosl.org              up              (Thu, 23 May 2024 05:21:53 UTC)
ftp-nyc.osuosl.org              up              (Sun, 31 Mar 2024 15:09:04 UTC)
archives.jenkins.io             disabled        (Sat, 24 Feb 2024 18:35:46 UTC)
sg.mirror.servanamanaged.com    up              (Tue, 28 Feb 2023 20:42:14 UTC)
hostico                         down            (Mon, 01 Jan 0001 00:00:00 UTC)
```

Trying a full refresh and/or restart let's see

**Comment by dduportal** [comment]
During a team debugging session, we discovered that the date in the column `SINCE` maps to the last "state" change internally (ref. https://github.com/etix/mirrorbits/blob/53725c9d3ba2e676ed40a9d35dd7b0dc9d858817/cli/commands.go#L209).

It means the command `mirrorbits add` is buggy in this case: despite removing and re-adding (also tried to refresh and pod deletion), the initial state was always stuck.

However, by using the `mirrorbits edit <...>` command, we we able to force a state change (mirrorbits bug?).

**Comment by dduportal** [comment]
https://get.jenkins.io/windows-stable/2.452.1/jenkins.msi?mirrorlist shows the Hostico mirror as expected: victory \o/

**Comment by dduportal** [comment]
![Capture d’écran 2024-06-10 à 16 23 47](https://github.com/jenkins-infra/helpdesk/assets/1522731/baf7b034-efdc-40f1-bc08-71b022d14f9a)

**Comment by lemeurherve** [comment]
For the record: https://github.com/jenkins-infra/helpdesk/issues/4147#issuecomment-2196603847

> Proposal based on the above comments from different users + internal discussions:
> 
> - Set Yandex mirror to Russian country only => this mirror would only be selected for Russian users
> - All East-Europe traffic will get to Hostico due to this one => if is not sustainable for them, then we'll also restrict them to Romania only
> - It means, in the worst case scenario, we'll back to the situation one month ago with traffic going to Germany and/or Belgium (except for Russian and Romania) so still better than before
> 
> Any objection of thing to consider if we set up this change next week?
