### ISSUE TITLE
Upgrade spotinst-plugin to java 11 while supporting users with Java 8

### ISSUE THREAD

**Issue by sitay93** [jenkins-infra/helpdesk#4014]
### Service(s)

plugins.jenkins.io

### Summary

Hello,
To support customer requirements on latest Jenkins versions, we need to upgrade our plugin's Java version from Java 8.
The problem we're encountering is, that we want to preserve the option for customers to keep using Java 8, if they choose to.
What is the best practice you recommend, if we want to have 2 "forks" of the plugin, for those 2 options?
Thanks

**Comment by MarkEWaite** [comment]
Thanks for sincerely caring about users.  That's great!

The [plugin and core versions report for the spotinst plugin](https://stats.jenkins.io/pluginversions/spotinst.html) shows that:

* 97% of the installations of the 2.2.15 release (most recent for which there is installation data) are already running on Jenkins versions that require Java 11.  The users that are upgrading to the most recent plugin release are already running Java 11.  Since 2.2.15 released 6 months ago, the users have had plenty of time to evaluate the release and upgrade to it
* 90% of the installations of the 2.2.13 release (released 11 months ago) are already running on Jenkins versions that require Java 11
* 91% of the installations of the 2.28 release (released 2 years ago and has the most installations of any version) are already running on Jenkins versions that require Java 11
* 65% of all of the spotinst plugin installations are already running on a Jenkins version that requires Java 11

With those results, I think that you are safe to move to Java 11 without retaining Java 8 builds.  2.2.15 has only 1 installation that is not already using Java 11.  2.2.13 has 2 installations that are not already using Java 11.

The Jenkins update center data is only published for releases that are up to a year old.  The last Jenkins core release that supported Java 8 is more than a year old.  Users seeing a plugin update on those controllers running Java 8 must choose very carefully if they will install the plugin or not.

If you still decide that you want to continue supporting Java 8, then a branch for Java 8 is the way to do it, with releases from that branch.

**Comment by MarkEWaite** [comment]
> is there a way to have these 2 branches and for the, to be available for users to choose?

In this case, the user experience is not easy, but it is possible.

You would create a branch that is dedicated to the Java 8 line, probably using the version numbers that are currently on the master branch.  That branch is often called something like "stable-2.2` or `stable-2`.  Then you modify the master branch to use a new version (like 2.3).  You commit changes to the master branch to require Java 11 and a newer Jenkins version as guided by the [Improve a Plugin tutorial - Update Jenkins version](https://www.jenkins.io/doc/developer/tutorial-improve/update-base-jenkins-version/)

When you release from the `stable-2.2` branch, a new release (like 2.2.16) will be created.  Users of those old Jenkins versions might see those releases as available to them, depending on the minimum Jenkins version required by releases from the master branch.  If the minimum Jenkins version on the master branch is too old, a new release from the master branch (like 2.3.0) may be shown to the Java 8 user instead of your 2.2.16 release from the stable-2.2 branch.  I'm not entirely sure on all  the details of this behavior.  I think that it is unwise to encourage users to remain on an old Jenkins version while still updating their plugins.  If they update plugins, they should update Jenkins core.

In any case, users running a Java 8 based version of Jenkins can always download the 2.2.16 plugin binary use the plugin manager's "Advanced" tab to install it.
