### ISSUE TITLE
No email received after signing up

### ISSUE THREAD

**Issue by Maikoding** [jenkins-infra/helpdesk#4066]
### Type(s) of account issue

I didn't receive any email

### Summary

After the sign up process where I was redirected to the page to check my email. I cannot find any mail from the jenkins service.

### jenkins.io account username

Maikoding

### jenkins.io account email

blackzero.2011@web.de

### Which URL are you trying to login at?

https://accounts.jenkins.io/signup

**Comment by dduportal** [comment]
Hi @Maikoding , as we can see your account is created and you tried to reset your password twice.

But our email address was marked as not existing by the `web.de` system when the first email was sent (`SMTP 550 Error: Requested action not taken: mailbox unavailable`) and as such was bounced since then.

We've sent you an email directly : can you please answer it to ensure your email works as expected?

**Comment by Maikoding** [comment]
Hi @dduportal;
thank you for taking up this issue. 
I finally received the email from jenkins.io regarding the pw.
As soon I completed my user account in jenkins I let you know in order to close this issue.
Br
Maik

**Comment by Maikoding** [comment]
Account is created successfully thank you for you investigation on this topic.
I will close this issue.
Br 
Maik
