### ISSUE TITLE
Delate account and update the default assignee for the atlassian-jira-software-cloud-plugin

### ISSUE THREAD

**Issue by rafalmyslek** [jenkins-infra/helpdesk#4067]
### Type(s) of account issue

I want my account to be deleted

### Summary

This is a follow-up of my previous request: https://github.com/jenkins-infra/helpdesk/issues/3175

I've requested to delete my account and change the default atlassian-jira-software-cloud-plugin asignee to @bgvozdev.

Turns out my account hasn't been deleted and I'm still the default assignee, see the recently created ticket:  https://issues.jenkins.io/browse/JENKINS-73040

### Which URL are you trying to login at?

accounts.jenkins.io

**Comment by dduportal** [comment]
Hi @rafalmyslek !

- I confirm that your account has been deleted in our LDAP system in 2022 (in #3175) => No login can be done anywhere since that deletion.
- Usually, we do not delete the JIRA comments to ensure the history of issues and comments does not looks weird. However we disable the JIRA account which are only "proxies" to the real LDAP accounts and it removes the email in JIRA (to avoid notifications)
- It looks like that https://github.com/jenkins-infra/helpdesk/issues/3851 had unintended consequences: restoring older data re-added your "disabled" account in JIRA (and only in JIRA).

I've updated the JIRA setup to fix this issue:

- Moved back the component lead to @bgvozdev as per https://github.com/jenkins-infra/helpdesk/issues/3175#issuecomment-1280097798. If it is a mistake, please tell us!

<img width="319" alt="Capture d’écran 2024-04-29 à 19 44 46" src="https://github.com/jenkins-infra/helpdesk/assets/1522731/f961cc45-4d2b-4986-870d-e1f8c362b11b">

- Changed the email of your former account (the "proxy account") in JIRA to disabled-helpdesk-4067@jenkins.io to ensure you're not spammed anymore!

- Confirmed that JIRA saw your last login in 2022-10-14 (e.g. same date as your initial request)

Does it look good for you @rafalmyslek?

**Comment by rafalmyslek** [comment]
The changes look good. Thank you very much for sorting this out.

**Comment by dduportal** [comment]
Thanks for confirmation @rafalmyslek and for your contributions to the Jenkins project!
