### ISSUE TITLE
Can't sign up to Jenkins Jira for reporting issue about a plugin.

### ISSUE THREAD

**Issue by noor-muradi** [jenkins-infra/helpdesk#4077]
### Type(s) of account issue

I've been blocked by the anti-spam system

### Summary

I am trying to submit an issue about a Jenkins plugin, but I cant sign up to Jira, as I got blocked by anti-spam system.

### jenkins.io account username

noor_muradi

### jenkins.io account email

noor.muradi@protonmail.com

### Which URL are you trying to login at?

account.jenkins.io/signup

**Comment by dduportal** [comment]
Hi @noor-muradi , thanks for opening this issue.
As administrator, I've manually created your account: please check your email inbox for instructions.


Note for the infra team: this account creation request has been blocked by the anti-spam system due to the public IP used: https://github.com/jenkins-infra/account-app/blob/cec268a6e85520cdcce88c631480233e8e45829b/src/main/java/org/jenkinsci/account/Application.java#L1175

**Comment by dduportal** [comment]
Note: opened https://github.com/jenkins-infra/account-app/pull/370 to ensure the Ip range is not a blocker anymore (and avoid a third case like this one or #4083)
