### ISSUE TITLE
perfecto plugin: 401 error on running "mvn release:perform" for user genesisthomas

### ISSUE THREAD

**Issue by genesis-thomas** [jenkins-infra/helpdesk#4088]
### Service(s)

Artifactory

### Summary

user: genesisthomas
I'm trying to release perfecto plugin but I keep getting 401 error on running "mvn release:perform" 

MVN error:
Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy (default-deploy) on project perfecto: Failed to deploy artifacts: Could not transfer artifact io.jenkins.plugins:perfecto:hpi:1.25 from/to repo.jenkins-ci.org (https://repo.jenkins-ci.org/releases): status code: 401, reason phrase:  (401) -> [Help 1]
---------
I can login at https://accounts.jenkins.io/  as well as https://repo.jenkins-ci.org/ui/login/ 
Note: genesisthomas is my older GitHub account that was part of this plugin release. I still ave access to it

### Reproduction steps

Using user: genesisthomas and trying to release perfecto plugin

**Comment by dduportal** [comment]
Quick check on the infra setup for the username `genesisthomas`:

- RPU is properly set up: https://github.com/jenkins-infra/repository-permissions-updater/blob/1c9946ef90318d92a19304c93030d1a39f49d654/permissions/plugin-perfecto.yml#L10
- No errors for RPU builds in the (private) controller since the past 24h (so the tokens on Artifactory should be generated and valid)
- The username `genesisthomas` in Artifactory has the proper permission set for the `perfecto` plugin

=> It does not look like an infrastructure error

**Comment by dduportal** [comment]
Hi @genesis-thomas , the HTTP/401 error indicates that the couple username + password set up *inside* your Maven settings is refused by Artifactory.
As you can login at  bothhttps://accounts.jenkins.io/ and https://repo.jenkins-ci.org/ui/login/, could you check your setup please?

The documentation at https://www.jenkins.io/doc/developer/publishing/releasing-manually/ is a good first step. However, be careful regarding the `<id>`: you might have to update it to map to your project (I did not had time to check if the `pom.xml` of the perfecto plugin and the associated parent pom version have the correct setup: an `mvn` effective pom might help you).

**Comment by genesis-thomas** [comment]
Thanks @dduportal. <id> was the issue
