### ISSUE TITLE
Unable to login to jenkin account

### ISSUE THREAD

**Issue by spsahu** [jenkins-infra/helpdesk#4091]
### Type(s) of account issue

I've lost my password, I didn't receive any email

### jenkins.io account username

swarnaprava

### jenkins.io account email

sprava198@gmail.com

### Which URL are you trying to login at?

https://issues.jenkins.io/login.jsp

**Comment by MarkEWaite** [comment]
There is no user account on https://accounts.jenkins.io for either the user name "swarnaprava" or for the email address "sprava198@gmail.com".  Since there is no account with that name, the Jenkins infrastructure help desk can't assist with a password reset.

You'll need to contact the administrators of the Jenkins controller for their help with the user account.  It is not an account in the Jenkins infrastructure.
