### ISSUE TITLE
retrieve my id and password

### ISSUE THREAD

**Issue by rajeeeeee** [jenkins-infra/helpdesk#4098]
### Type(s) of account issue

I didn't receive any email

### Summary

i have forget id username and password

### jenkins.io account username

RAJE-

### jenkins.io account email

rajrajee04@gail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
Hi @rajeeeeee , there is no account associated with this username or this email.

If you want to reset your Jenkins controller access, please check with your administrator.

If you want to have an account for the public `*.jenkins.io` website (such as the Jenkins public issue tracker at issues.jenkins.io), please create one instead of trying to recover something that does not exist.
