### ISSUE TITLE
account  recovery

### ISSUE THREAD

**Issue by krishj73** [jenkins-infra/helpdesk#4112]
### Type(s) of account issue

I didn't receive any email

### Summary

i'm unable to sign in, so i tried forgot password method but didn't receive any email

### jenkins.io account username

Krish

### jenkins.io account email

krishjaisingh73@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
Hi @krishj73 , there isn't any account associated with this email address which explains why you receive nothing.

The user `krish` (lowercase) exists but it is associated with another email.

- If you are sure you want to reset the password of this user account to access issues.jenkins.io or ci.jenkins.io, then please access the correct email (where the password reset instructions have been sent) to prove this is your user account.
- Otherwise you can create a fresh new account
