### ISSUE TITLE
Forget password

### ISSUE THREAD

**Issue by saigattoji** [jenkins-infra/helpdesk#4176]
### Type(s) of account issue

I didn't receive any email

### Summary

I haven't recieve any email so far 

### jenkins.io account username

sai

### jenkins.io account email

gattojisaikumar94@gmail.com

### Which URL are you trying to login at?

account.jenkins.io/passwordReset

**Comment by dduportal** [comment]
Hi @saigattoji , there are no account associated with your email address, but note that the username `sai` is already taken.

- If you want to reset the password of your own (or your organization's) Jenkins controller then contact your administrators: this issue tracker is only for the public Jenkins infrastructure and websites
- If you need to create an account for issues.jenkins.io, in that case please create it with your email and another username
- If you are the rightful owner of the existing `sai` account, then you have to access the associated email (that should be aware of) otherwise the account won't be available (as there would be no other way to prove you are the rightful owner)
