### ISSUE TITLE
forgot username and password

### ISSUE THREAD

**Issue by AmnahAhmad** [jenkins-infra/helpdesk#4187]
### Type(s) of account issue

Other (please describe in the summary below)

### Summary

i forgot username and password for my jenkins account.

### Which URL are you trying to login at?

https://accounts.jenkins.io/login

**Comment by MarkEWaite** [comment]
If you've forgotten your username and your password for a Jenkins account that is administered by the Jenkins infrastructure team, then there is not much we can do to help you.  The account is lost and unusable.  The best you can do is to create a new account through https://accounts.jenkins.io and use that account.

If you've forgotten your username and your password for a Jenkins account that is **not** administered by the Jenkins infrastructure team, then there is nothing we can do to help you.  If the Jenkins infrastructure team does not administer the account, we can't help with an account issue.

Since both cases have nothing that the Jenkins infrastructure team can do, I'm closing this request as not planned.
