### ISSUE TITLE
Downloads of `git-changelist-maven-extension` from plugin build failing

### ISSUE THREAD

**Issue by jglick** [jenkins-infra/helpdesk#4194]
### Service(s)

Artifact-caching-proxy, ci.jenkins.io

### Summary

https://github.com/jenkinsci/active-directory-plugin/pull/188/checks?check_run_id=27857413496

```
The following artifacts could not be resolved: io.jenkins.tools.incrementals:git-changelist-maven-extension:pom:1.8 (absent): Could not transfer artifact io.jenkins.tools.incrementals:git-changelist-maven-extension:pom:1.8 from/to central (https://repo.maven.apache.org/maven2): repo.maven.apache.org: Try again
```

Since this is a Maven extension, it is loaded before the POM is parsed, and thus must be hosted in Central not Artifactory. It seems that CI builds are not set up to use a Central mirror?

### Reproduction steps

Try to get https://github.com/jenkinsci/active-directory-plugin/pull/188 to build in CI.

**Comment by MarkEWaite** [comment]
As far as I can tell from the [build log](https://ci.jenkins.io/job/Plugins/job/active-directory-plugin/job/PR-188/1/pipeline-console/?selected-node=125), that failure seems to be happening in a `docker run` environment that is invoked as a separate stage after the more common Linux and Windows build stages are successful.  I assume that some change is needed inside the container definition that is performing the `clean install -P onlyITs`

I'm not sure a change in that container image is something that the infra team should make, since I believe it will require code changes in the plugin repository.

**Comment by basil** [comment]
>Service(s)
> Artifact-caching-proxy, ci.jenkins.io

The Artifact Caching Proxy is not in use at the time of the failure. This ticket has been filed in error.

**Comment by dduportal** [comment]
I confirm: there are no artifact caching proxy involved in the stage with the `Docker build/run` commands. Thanks @basil and @MarkEWaite .

The error looks like a network issue in the DinD container. I do not see any valid reason to have the DinD container in this context as there is already a Docker CE engine: I'm opening a PR to propose (and verify) a pipeline change for this step

**Comment by jglick** [comment]
Ah: https://github.com/jenkinsci/active-directory-plugin/pull/83#issuecomment-1314035127
