### ISSUE TITLE
Suspend distribution of the windows-slaves-plugin

### ISSUE THREAD

**Issue by jtnord** [jenkins-infra/helpdesk#4221]
### Service(s)

Update center

### Summary

The [plugin](https://github.com/jenkinsci/windows-slaves-plugin/) has not worked for a few years with any version of Windows [that is secure](https://github.com/jenkinsci/windows-slaves-plugin/pull/43#issuecomment-2277518828).

As such I am proposing that the repo is archived and the plugin is suspended from the Update Center.

**Comment by MarkEWaite** [comment]
+1 from me.  We should probably also suspend distribution of the one plugin that depends on it, the [multi-slave config plugin](https://plugins.jenkins.io/multi-slave-config-plugin/).  The multi-slave config plugin was last released 10 years ago, has been deprecated for over 2 years, and does not have an active maintainer.

## Why I think that suspension is the right approach

We suspend distribution of plugins that depend on a service that no longer exists or is end of life like:

* https://github.com/jenkins-infra/update-center2/pull/755
* https://github.com/jenkins-infra/update-center2/pull/756
* https://github.com/jenkins-infra/update-center2/pull/732

This feels like a similar case to services that are end of life.  Windows is not end of life, but the services required for this plugin have been end of life since at least March 2023. The plugin was [deprecated](https://github.com/jenkinsci/windows-slaves-plugin?tab=readme-ov-file#notice-of-deprecation) almost [two years ago](https://github.com/jenkinsci/windows-slaves-plugin/commit/cdafd13807267b535b13bbb25d9cc72376aa4594).

The [plugin installation statistics](https://stats.jenkins.io/pluginversions/windows-slaves.html) show that there are still almost 80,000 installations of the plugin, but only 22% of those installations are on 2.426.3 or newer.

Users with the plugin already installed will not be affected by distribution being suspended.  Users with configuration as code definitions that include the plugin will need to remove it from their configuration as code definition.  They will receive an error message when they attempt to download the plugin version.

**Comment by MarkEWaite** [comment]
Distribution of the plugin has been suspended.
