### ISSUE TITLE
NA

### ISSUE THREAD

**Issue by Vimala-Daniel** [jenkins-infra/helpdesk#4239]
### Service(s)

jenkins.io

### Summary

I am having some issue with jenkins console after making some changes in config.xml file after which I was not able to view/execute any of the job , job option itself not showing up in dashboard page. Please need technical support.

I can share logs if you require for troubleshooting.

**Comment by dduportal** [comment]
Hi @Vimala-Daniel , this issue tracker is NOT the place to ask for support about your Jenkins instance.
Also, please do not spam project by asking your question on different locations: You've already asked on unrelated Matrix/Gitter channels (jenkinsci/ux-sig, jenkinsci/docs, etc.).

You have to ask the question on either the community forums at community.jenkins.io, or in jenkinsci/jenkins Matrix/Gitter channel (which you did and it is ok in this one).

And then, you will have to WAIT for a response. Note that people are helping on a base of good faith as this is an open source project, not a commercial one (check www.cloudbees.com if you need commercial support on Jenkins).
In order to get a more positive attention, you should had more information to help analysis:
- What version of Jenkins? What list of plugin (ID and versions)?
- How is Jenkins installed and running (what OS, what kind of package, etc.)?
- What did you do *exactly*? Do you have backup of the changed files?
- What was expected *exactly*?
- What do you see *exactly*?
- Logs, of course :)
