### ISSUE TITLE
ACP mirroring configuration prevents usage of external repositories

### ISSUE THREAD

**Issue by hashar** [jenkins-infra/helpdesk#4271]
### Reproduction steps

The [Jenkins Gearman plugin](https://github.com/jenkinsci/gearman-plugin/) depends on the gearman-java library which is not published on Maven Central. The plugin `pom.xml` has:
```    
<repositories>
        <repository>
            <id>wikimedia.releases</id>
            <name>Wikimedia Release Repository</name>
            <url>https://archiva.wikimedia.org/repository/releases</url>
        </repository>
</repositories>
```

Since the build failure on a dummy change https://github.com/jenkinsci/gearman-plugin/pull/19 / https://ci.jenkins.io/job/Plugins/job/gearman-plugin/job/acp-testing/1/console .

### Expected Results

For a new / unknown external repository, the maven configuration should not setup the mirror or ACP should support proxying requests to it.

### Actual Results

ACP does not have the external artifacts, the build fails:

If I try to build it via a GitHub pull request, the build fails due to `artifact-caching-proxy.privatelink.azurecr.io` not having the resource and eventually it fails with:
```
[WARNING] The POM for org.wikimedia.gearman:gearman-java:jar:0.10 is missing, no dependency information available
[ERROR] Failed to execute goal on project gearman-plugin: Could not resolve dependencies for project org.jenkins-ci.plugins:gearman-plugin:hpi:0.6.1-SNAPSHOT: org.wikimedia.gearman:gearman-java:jar:0.10 was not found in https://repo.jenkins-ci.org/public/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of repo.jenkins-ci.org has elapsed or updates are forced -> [Help 1]
```
```
11:56:59  dependency: org.wikimedia.gearman:gearman-java:jar:0.10 (compile)
11:56:59  	Could not find artifact org.wikimedia.gearman:gearman-java:jar:0.10 in azure-internal (http://artifact-caching-proxy.privatelink.azurecr.io:8080/)
```

https://ci.jenkins.io/job/Plugins/job/gearman-plugin/job/acp-testing/1/console

### Anything else?

Looking at https://github.com/jenkins-infra/documentation/blob/a5ef397cbe139ffe0477f39bd4600e3729f274f3/ci.adoc#artifact-caching-proxy I have send a pull request disabling ACP by labeling it with `skip-artifact-caching-proxy` and the build found the artifact ( https://github.com/jenkinsci/gearman-plugin/pull/18/ ).

I eventually found the mirroring configuration at https://github.com/jenkins-infra/jenkins-infra/blob/production/dist/profile/templates/jenkinscontroller/casc/artifact-caching-proxy.yaml.erb which has:
```
            <mirrors>
              <mirror>
                  <id><%= serverId %></id>
                  <url><%= serverConfig['url']%></url>
                  <mirrorOf>external:*,!chimera-releases,!chimera-snapshots,!atlassian-public,!org.zowe.sdk,!jitpack.io,!space-maven</mirrorOf>
              </mirror>
            </mirrors>
```

The `external:*` is from [Maven advanced mirror configuration](https://maven.apache.org/guides/mini/guide-mirror-settings.html):

> `external:*` matches all repositories except those using localhost or file based repositories. This is used when you want to exclude redirecting repositories that are defined for Integration Testing.

If I understand it correctly, it matches my external repository (`wikimedia.releases` defined in the plugin pom) and I suspect your ACP does not proxy requests back to our repository. The artifacts are thus not found and the build fails.

I imagine that is why there are exceptions such as `!chimera-releases`, `!jitpack.io`  or `!space-maven` (recently added as an exception by jenkins-infra/jenkins-infra#3314)?

Maybe the rule should be changed to mentions it caches `central` and not the external ones. Possibly it could be changed to:
```
central,!external:*
```

Else my repository should be added to the exception list (`!wikimedia.releases`) but it feels cumbersome to have to keep adding repositories to the list?

//for my later self, our bug is https://phabricator.wikimedia.org/T373352 //

**Comment by dduportal** [comment]
Hi @hashar , thanks for raisin the issue!

A few answers and directions from here:

> For a new / unknown external repository, the maven configuration should not setup the mirror or ACP should support proxying requests to it.

This is a behavior we do not want on ci.jenkins.io. The goal is to avoid (as much as possible : it is not absolute of course!) spreading dependencies everywhere. A certain level of "control -> check -> add" loopback is needed, otherwise we'll start having sustainability issues (disappearing dependencies, CVEs, supply chains attacks, etc.).
We do have solutions to help you though!

> If I understand it correctly, it matches my external repository (wikimedia.releases defined in the plugin pom) and I suspect your ACP does not proxy requests back to our repository. The artifacts are thus not found and the build fails.

Your understanding is correct. Your technical analysis has been right.

The pattern rule used by the `mirrorOf` comes from transitioning states we did from "everything in Jenkins Artifactory" to "only Jenkins dependencies in Jenkins Artifactory + Central + other minor repositories".
The exceptions are external artifact repositories which were audited or known to be trustable by the Jenkins community: as such they were "proxy-ied" in the Jenkins Artifactory before the state change above => this is the reason why these exception exists. I believe PRs such as https://github.com/jenkins-infra/jenkins-infra/pull/3314 were missing this explanation.


> Else my repository should be added to the exception list (!wikimedia.releases) but it feels cumbersome to have to keep adding repositories to the list?

That would be a solution yes. it's not that cumbersome as adding new artifact repository should not be something happening often (otherwise we would have quite some trouble really quickly...).

However I see that in https://phabricator.wikimedia.org/T373352 you tried (or are trying) to publish your artifacts to Maven Central. This solution is clearly recommended. I use to work with https://maven.apache.org/repository/guide-central-repository-upload.html to get guidance.

=> Given uploading to Maven central (at least initializing the publication process) may take some time, I recommend you to fix your builds with either (temporarily of course, until your dependencies are published to Maven Central):

- Keeping ACP disabled with the `useArtifactCachingProxy` attribute of the pipeline's `buildPlugin()` function set to `false`
- Use a file-based repository in your `pom.xml`. Maven will add this repository and won't try to use ACP to resolve its dependencies.

**Comment by hashar** [comment]
> However I see that in https://phabricator.wikimedia.org/T373352 you tried (or are trying) to publish your artifacts to Maven Central. This solution is clearly recommended. 

Thank you to have taken the time to dig in my original report. I will indeed change to use Maven Central as a distribution management.  Our domain (`org.wikimedia`) is still under the old OSSRH, I have to be added there and figure out how to import the old versions, but ultimately having everything on Central will simply things.

> Keeping ACP disabled with the `useArtifactCachingProxy` attribute of the pipeline's `buildPlugin()` function set to `false`

I will pick that road, I wasn't sure whether it might potentially cause issues on your CI infrastructure and I wanted to make sure I properly understood what was going on.

So my next steps are:
* `buildPlugin( useArtifactCachingProxy: false, ...)`
* Work on publishing the gearman-java library on Maven Central
* Remove `useArtifactCachingProxy`

I am quite happy I had the technical analysis right and your reply is nice example of being a great upstream. I am closing the issue since ACP not proxying to random external repositories is the expected behavior.

Thank you so much @dduportal !

**Comment by hashar** [comment]
As a follow up, I got gearman-java uploaded to Maven Central ( https://repo.maven.apache.org/maven2/org/wikimedia/gearman/gearman-java/0.10/ ).

I then redid my pull request to no more _disable Artifact Caching Proxy_  (4a671206711c8e182c8b88191684b3d365931770) and surely it passed this time https://github.com/jenkinsci/gearman-plugin/pull/18


Again thank you @dduportal for your assistance!

**Comment by dduportal** [comment]
> As a follow up, I got gearman-java uploaded to Maven Central ( https://repo.maven.apache.org/maven2/org/wikimedia/gearman/gearman-java/0.10/ ).
> 
> I then redid my pull request to no more _disable Artifact Caching Proxy_ (4a671206711c8e182c8b88191684b3d365931770) and surely it passed this time [jenkinsci/gearman-plugin#18](https://github.com/jenkinsci/gearman-plugin/pull/18)
> 
> Again thank you @dduportal for your assistance!

Great work! Thanks for your contributions! (and thanks for the feedbacks ;) )
