### ISSUE TITLE
unexpected plugin versions being returned by update-center

### ISSUE THREAD

**Issue by mattdgsg** [jenkins-infra/helpdesk#4272]
### Service(s)

Update center

### Summary

I may be misunderstanding how this is supposed to work, but the update-center seems to be returning plugin versions that are incompatible with the Jenkins version passed as a query parameter. For example:

```
$ curl -skSL https://updates.jenkins.io/update-center.actual.json?version=2.401.2 | jq -r '.core.version'
2.462.1
```

Based on the documentation (and previous issues I've found), I took this to mean that the plugins for 2.462.1 are compatible with version 2.401.2. But the plugins themselves report higher version requirements:

```
$ curl -skSL https://updates.jenkins.io/update-center.actual.json?version=2.401.2 | jq -r '.plugins."jersey2-api".requiredCore'
2.401.3
```

Is this expected?

**Comment by MarkEWaite** [comment]
This is the expected behavior for Jenkins versions that are no longer supported by the Jenkins update center.  The Jenkins update center only provides information for a limited range of releases.  The oldest LTS version in that range of releases is currently Jenkins 2.401.3.  In a month or less, that oldest LTS version will be 2.414.1.

The ["Choosing a Jenkins version" page](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/) lists the current versions and says:

> ... versions no longer supported by the update center, which is currently anything older than 2.415 for weekly releases, and 2.401.3 for LTS releases. Note that the lowest supported version changes about every week (weekly release) or every month (LTS release), so these specific versions will be a bad choice soon.

The best advice is to upgrade your Jenkins version, especially since there are critical security vulnerabilities in Jenkins versions older than 2.440.3 that are being actively exploited.
