### ISSUE TITLE
[updatecli][2024-09] YAML cleanups and tracking missing dependencies

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/helpdesk#4280]
We have a few updatecli manifests which deserves cleanup or addons:

- https://github.com/jenkins-infra/jenkins-infra/issues/3645
- https://github.com/jenkins-infra/kubernetes-management/issues/5663
- https://github.com/jenkins-infra/packer-images/issues/1381

**Comment by dduportal** [comment]
Update: added a 3rd item (https://github.com/jenkins-infra/packer-images/issues/1381)

**Comment by jayfranco999** [comment]
Update: Added updatecli manifest to track the latest version of mirrorbits CLI from the GH repo.

Tested locally and successful (rolled-back mirrorbits version to check the solution) - https://github.com/jenkins-infra/jenkins-infra/issues/3645#issuecomment-2331640733

**Comment by jayfranco999** [comment]
Update: https://github.com/jenkins-infra/kubernetes-management/issues/5663

We updated all manifest tracking Helm Charts versions to use YAML path targets instead of file targets.

It allows using YAML path queries to perform selection of the list object based on attribute filters which was the proposed solution.

**Comment by jayfranco999** [comment]
Update: https://github.com/jenkins-infra/packer-images/issues/1381

For tracking the Maven version we switch to the new source of type dockerfile which is easier to read and maintain. (https://github.com/jenkins-infra/packer-images/pull/1384)

Tested and successful locally.

**Comment by dduportal** [comment]
Nice job!
