### ISSUE TITLE
[terraform-aws-sponsorship] updatecli manifest for outbound ips

### ISSUE THREAD

**Issue by smerle33** [jenkins-infra/helpdesk#4352]
following https://github.com/jenkins-infra/terraform-aws-sponsorship/pull/23 we will need an updatecli manifest to track the ips from https://reports.jenkins.io/jenkins-infra-data-reports/azure-net.json

**Comment by dduportal** [comment]
- Suggestion to fix https://github.com/jenkins-infra/terraform-aws-sponsorship/pull/23
- Then, list all IPs introduced in the PR
- For each IP:
  - If it is in the reports (https://reports.jenkins.io/jenkins-infra-data-reports/) then track it with updatecli
  - Otherwise ping us asking for help (so we can add the missing IP in the reports)

**Comment by dduportal** [comment]
Ping @jayfranco999 : since https://github.com/jenkins-infra/azure-net/pull/315, the VPN outbound IP is now available in https://reports.jenkins.io/jenkins-infra-data-reports/azure-net.json

**Comment by jayfranco999** [comment]
As https://github.com/jenkins-infra/terraform-aws-sponsorship/pull/34 is merged, this issue can be closed.
