### ISSUE TITLE
The archives.jenkins.io SSL certificate does not renew, expires in 25 days

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/helpdesk#7]
### Service

Archives

### Summary

The SSL certificate on https://archives.jenkins.io renews correctly in the local copy on the server, but that local copy is not used by the Apache web server.  Even after applying operating system updates and restarting the server, the SSL certificate for https://archives.jenkins.io and for https://archives.jenkins-ci.org still reports that it will expire in 25 days

When the `certbot renew` command is run on that server, it reports that renewal is not needed because the most recent certificate on the machine will not expire until April, 2022.  Unfortunately, the certificate that is being used by Apache reports that it will expire Feb 1, 2022.

### Reproduction steps

1. Report the SSL certificate expiration date of archives.jenkins.io with the command
```
$ curl --insecure -vvI https://archives.jenkins.io 2>&1 | \
   awk 'BEGIN { cert=0 } /^\* SSL connection/ { cert=1 } /^\*/ { if (cert) print }'
```
2. Report the SSL certificate expiration date of archives.jenkins-ci.org with the command
```
$ keytool -printcert -sslserver archives.jenkins-ci.org | head
```

**Comment by dduportal** [comment]
Renewal fixed with the help of @lemeurherve.

The site archives.jenkins.io is now using the certificates expiring on April:

```shell
curl --insecure -vvI https://archives.jenkins.io 2>&1 |    awk 'BEGIN { cert=0 } /^\* SSL connection/ { cert=1 } /^\*/ { if (cert) print }'
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=archives.jenkins.io
*  start date: Jan  2 00:45:09 2022 GMT
*  expire date: Apr  2 00:45:08 2022 GMT
```

The content of the directory `/etc/letsencrypt/live/archives.jenkins.io` was pointing to certificate files located in the `/etc/letsencrypt/archives/...` directory, while the certificates renwed by certbot are located in `/etc/letsencrypt/live/archives.jenkins.io-0061`.

We fixed the symlinks and restarted apache2.

A backup of the old symlinks had been kept in `/root` on the VM just in case we have to rollback.

**Comment by dduportal** [comment]
An event is added in the team calendar to check for the next renewal, ~25 days before the 2th of April.
